### ISSUE TITLE
Snippets not working properly

### ISSUE THREAD

**Issue by steelbrain** [atom/autocomplete-plus#663] opened 2016-02-03 02:15 UTC
We've run into a mysterious error

![screenshot](https://cloud.githubusercontent.com/assets/4278113/12770844/2d3a624e-c9e1-11e5-8282-9b1d8bb09311.png)

That snippetted item when expanded, acts like a text item

See https://v.usetapes.com/qkQisJcd2z

**Comment by 50Wliu** [comment] 2016-02-03 02:22
This is a duplicate of #661 - feel free to subscribe there for updates.

**Comment by steelbrain** [comment] 2016-02-03 02:23
Ah, I searched for `snippet` before opening a new issue, I guess the title got ignored. Sorry about the dupe

**Closed by 50Wliu** 2016-02-03 02:22 UTC
