### ISSUE TITLE
Snippets still aren't html escaped

### ISSUE THREAD

**Issue by nosami** [atom/autocomplete-plus#536] opened 2015-07-18 03:55 UTC
Sorry to have to tell you this, but it seems that this [bug](https://github.com/atom/autocomplete-plus/issues/466) is still there in v1.0.2

Look at the 2nd item here `AddRange(IEnumerable collection)`

<img width="571" alt="parameters not escaped" src="https://cloud.githubusercontent.com/assets/667194/8760238/38cd240a-2d08-11e5-9b63-c74841161a0d.png">

It should be `AddRange(IEnumerable<string> collection`
<img width="381" alt="completion result" src="https://cloud.githubusercontent.com/assets/667194/8760237/37961fb0-2d08-11e5-93dd-cb407d3e525a.png">

Although it looks as though other parts of the completion are escaped now... I can see `<` and `>` elsewhere, just not inside the paramater snippets.

<img width="358" alt="completions are escaped" src="https://cloud.githubusercontent.com/assets/667194/8760236/36f30032-2d08-11e5-89ac-e3821b224e62.png">

**Comment by benogle** [comment] 2015-07-21 22:18
What version of atom are you on? Can you paste in an example suggestion hash? What package is generating this list?

They are being escaped for me: 

![screen shot 2015-07-21 at 3 16 11 pm](https://cloud.githubusercontent.com/assets/69169/8813873/83589bf2-2fbb-11e5-9ce4-ad3355b5492a.png)

**Comment by benogle** [comment] 2015-07-21 22:28
I wonder if it has to do with [escaping here](https://github.com/OmniSharp/omnisharp-atom/blob/da2ce8cef52c51bbb22ee824357c24b2286c388a/lib/omnisharp-atom/features/lib/completion-provider.ts#L169). An example suggestion hash would be amazing

**Comment by benogle** [comment] 2015-07-22 22:47
Closing this as fixed. I am unable to reproduce. @nosami if there is still an issue, please reopen with an example hash of what you are passing back to ac+.

**Closed by benogle** 2015-07-22 22:47 UTC
Labels: more-information-needed
