### ISSUE TITLE
Crashes Atom when used with pigments

### ISSUE THREAD

**Issue by ProLoser** [atom/autocomplete-plus#429] opened 2015-05-01 23:07 UTC
When used with `pigments` only, simply writing a few characters in a `scss` file causes the entire editor to crash.

See https://github.com/abe33/atom-pigments/issues/7

**Comment by benogle** [comment] 2015-07-21 23:52
@abe33 is this still an issue?

**Comment by mnquintana** [comment] 2015-07-21 23:55
I haven't ever managed to reproduce this, and I've been using pigments in SCSS files for a long time now.

**Comment by benogle** [comment] 2015-07-21 23:56
Rad, closing.

**Closed by benogle** 2015-07-21 23:56 UTC
Labels: conflicts-with-other-package

**Comment by abe33** [comment] 2015-07-22 07:53
It should have been fixed for some time now, it was due to the way I was evaluating the variables found in a project as a color when building the autocomplete array. Now I use a collection that manage that in a more granular way so that we don't have to evaluate variables except when they or on their dependencies is modified.

**Comment by simpsondigital** [comment] 2015-09-05 03:35
Think there is still an issue with Pigments. Crashing Atom hard for me. I've narrowed it down to that plugin, and every time I re-enable it, Atom becomes entirely unresponsive. Running OS X 10.10.5.

**Comment by lee-dohm** [comment] 2015-09-05 03:59
@simpsondigital You should probably open an Issue on the [pigments package](https://atom.io/packages/pigments) if there isn't one already.

**Comment by simpsondigital** [comment] 2015-09-05 04:20
I did indeed, thanks for the reply.
