### ISSUE TITLE
completions wipe out subsequent word if it's the same

### ISSUE THREAD

**Issue by zyklus** [atom/autocomplete-plus#559] opened 2015-08-10 03:38 UTC
Put the cursor before any word.  Start typing the word following the cursor.  Wait for auto-complete popup and accept that word.  The following word gets wiped out.

![clip-text](https://cloud.githubusercontent.com/assets/320562/9159127/38af5678-3f55-11e5-8e39-fddb392c03f3.gif)

(`|` is a cursor)
```
|resolve
reso|resolve   # Now select "resolve" from the drop down
resolve|

# expected:
resolve|resolve
```

Atom 1.0.5, OSX 10.10.4

**Comment by jeancroy** [comment] 2015-08-10 14:17
What's your use case for duplicating word ?
I'm pretty sure behavior is intentional and is sometime wanted.
So maybe there's some pattern in when it's wanted and when it's not.

**Comment by zyklus** [comment] 2015-08-10 14:33
@jeancroy -- please see the gif I posted, the use case is pretty clear there.  Basically I don't want to duplicate a word, I'm just in the middle of typing "word....word", generally an object.

This is a case of "software trying to be too smart" and I can't see any point to this "feature".  If the word is already there, why would I be typing it?

As you pointed out, why would I be duplicating a word?  I obviously wouldn't be, so the only real use case is in the middle of typing something else, which this ever so helpfully just gets in the way of.

**Comment by zyklus** [comment] 2015-08-14 18:00
Just ran into another use case.  Notice how the same word is annoyingly wiped out:

![flatten](https://cloud.githubusercontent.com/assets/320562/9280500/5f9e4f24-42f1-11e5-9d9e-816c9f75c35a.gif)

**Comment by vjau** [comment] 2015-09-13 08:21
I miss a feature from Webstorm/IntelliJ Idea that replace everything under the cursor when choosing autocomplete suggestion ! 
Actually Webstorm isn't even smart, it replaces EVERYTHING (until next space) under the cursor.
At first, if found this sometimes annoying, but most of the time very useful. In the few cases when you don't want what's under the cursor to be replaced, you hit the space key instead of the tab key and the content is not repaced.
What's the point of this ? Most of the time, when i put the cursor under some existing function name, variable name, or what you want, it's to replace it. 
With actual autocomplete plus behaviour, i have to input the replacing word and then wipe the replaced word by hand, this is annoying. 
This could be perhaps an option ?
So

**Comment by zyklus** [comment] 2015-09-13 08:29
@vjau -- I'm having a hard time following what you're saying.  Can you give an example?

**Comment by vjau** [comment] 2015-09-13 08:51
Let's say i have a function call like this :
`foobazich(stuff)`;
Now, i changed my mind, and i want to replace foobazich with a call to  barbatruc.
I put the cursor before (or under) the f, start typing bar, and then autocomplete make a list of suggestions including barbatruc.
Under webstorm, if i go to the barbatruc entry and hit TAB, foobazich is replaced in place by barbatruc, and i get `barbatruc(stuff)`, without any additional manipulation. If instead i don't want this replacing to happen, i hit SPACE instead of TAB, and i end up with `barbatruc foobazich(stuff)`.
But most of the time, it is the replacing that is useful for me, and so i miss this behaviour in Atom.

**Comment by zyklus** [comment] 2015-09-13 08:57
gah, that would drive me crazy!  I can see how some people would like it though :)

Personally I accomplish the "same thing" by tapping CMD+D first, which highlights `foobazich` then I just start typing and it gets wiped out.

**Comment by jeancroy** [comment] 2015-09-13 16:12
I beleive this is the same issue as https://github.com/atom/autocomplete-plus/issues/468

**Comment by benogle** [comment] 2015-09-16 23:58
Closing as a dupe of #468. 

I am still inclined to keep this as is. A setting could be an option. PRs welcome.

**Closed by benogle** 2015-09-16 23:58 UTC
