### ISSUE TITLE
Mixed HTML and PHP results in constant autocompletion insertion of PHP open tags

### ISSUE THREAD

**Issue by repertor** [atom/autocomplete-plus#927] opened 2017-11-18 15:14 UTC
I'm working on a WordPress theme, and so mixed PHP and HTML content is the way...

Every time I type HTML content, the autocompleter wants to complete it as `<?php`, which means that at the end of each line I have to back up and delete the inserted content. I turned off the option of _Automatically Confirm Single Suggestion_ because it was the only suggestion.

I'm not sure what's leading to this—perhaps it's being confused by the mixed content. For instance, PHP code blocks can be interrupted by closing PHP tags `?>`, HTML thrown in for a time, then resumed with `<?php`. In researching the issue I've had I've found that this mixing has caused issues for other packages.

### Steps to Reproduce

1. Type some HTML in a PHP file
2. Ignore autocomplete because you're typing new code, press enter at end of line

**Expected behavior:** 
There should not be any matching at all

**Actual behavior:** 
Autocomplete inserts an errant tag

**Reproduces how often:**
Every time

### Versions
Atom 1.23.0-beta1
macOS 10.13.1

### Additional Information

![screen shot 2017-11-18 at 10 03 28 am](https://user-images.githubusercontent.com/5770553/32981905-3b59fe40-cc49-11e7-87e2-72529384bd39.png)

**Comment by 50Wliu** [comment] 2017-11-18 16:17
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/ide-php#47. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-18 16:17 UTC
