### ISSUE TITLE
Support parent directory

### ISSUE THREAD

**Issue by theaqua** [atom/autocomplete-plus#539] opened 2015-07-20 18:17 UTC
See details at [atom-autocomplete-modules/issues/9](https://github.com/nkt/atom-autocomplete-modules/issues/9).

**Comment by benogle** [comment] 2015-07-20 18:24
Please elaborate, I dont understand.

**Comment by theaqua** [comment] 2015-07-20 18:34
I'm using package [atom-autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) for import modules in ES6.

This package depends on autocomplete-plus and, as @nkt [says](https://github.com/nkt/atom-autocomplete-modules/issues/9#issuecomment-120452616), autocomplete-plus have limitation of parent directories. Is he right?

**Comment by jeancroy** [comment] 2015-07-20 20:25
So the issue is that `../l` autocomplete, but `../` don't ? 
Somehow I believe it's expected because there are no folder named `../` so that string only place search context. Then atom-autocomplete-modules filter for the rest of the string which is "" in the case that does not work.

For now i'm pretty sure the best place to fix it is in  atom-autocomplete-modules

----------

But i have another question, should fuzzaldrin.filter return the whole list when there's nothing to filter against ?

**Comment by benogle** [comment] 2015-07-21 21:53
Autocomplete will display anything a provider wants to display. This could be directories, parent directories, 80's movie names, grocery list items, etc. Closing this as I am not seeing the limitation in autocomplete.

**Closed by benogle** 2015-07-21 21:53 UTC
Labels: more-information-needed

**Comment by theaqua** [comment] 2015-07-22 08:46
@benogle thanks for help, I'll digging into `atom-autocomplete-modules` source code and make PR.
