### ISSUE TITLE
minimum word length bug - suggests after one character

### ISSUE THREAD

**Issue by captainquinn** [atom/autocomplete-plus#915] opened 2017-11-06 20:27 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocomplete-plus provides suggestions after a single character, regardless of what I set the minimum word length to in settings.  If I set minimum word length to 4, it will correctly not show suggestions after two or three characters, but it still shows suggestions after typing one character.  

This is a problem because
a) it's visually distracting/annoying
b) if you have the Keymap for Confirming a Suggestion set to the default "Tab and Enter" (which should be called "Tab or Enter" for clarity's sake), confirmations implement at undesired and unexpected times, e.g. typing _x=b_ and then hitting Enter changes the line to _x=bug_ 

### Additional Information

The suggestions after a single character have a green return symbol next to them, unlike suggestions after the minimum word length has been reached (see attached screenshot)

<img width="271" alt="screen shot 2017-11-06 at 12 25 37 pm" src="https://user-images.githubusercontent.com/1731695/32462259-a792be2c-c2ed-11e7-8f93-54b1f453a1a3.png">

Disabling autocomplete-plus eliminates the issue, so the cause is definitely not a different autocomplete package butting in

Thanks for the help!

**Comment by leroix** [comment] 2017-11-15 22:01
I'm going to close this as a duplicate of https://github.com/atom/autocomplete-plus/issues/795.

**Closed by leroix** 2017-11-15 22:01 UTC

**Comment by captainquinn** [comment] 2017-11-17 19:07
Sorry for the duplication - I searched for minimum word length, but didn't see this in the results for some reason...

There is one aspect that still baffles me, which is that disabling autocomplete-plus while autocomplete-snippet is still enabled makes the problem disappear.  But I'm posting that quandary over in 795.
