### ISSUE TITLE
Autocomplete don't work within the tags

### ISSUE THREAD

**Issue by sanada01** [atom/autocomplete-plus#1029] opened 2019-04-15 08:23 UTC
### Description

Autocomplete don't work within the tags

### Steps to Reproduce

1. Open a new .html file
2. Open a li tag, and open a tag within li tag

![33762836-6d991844-dc0e-11e7-927f-6c6c93067786](https://user-images.githubusercontent.com/28780118/56117442-5c393000-5f68-11e9-9d97-97e4185b4661.gif)

**Reproduces how often:** 100%

### Versions

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python
git 2.20.1.windows.1
visual studio

### Additional Information

[A long-standing bug.](https://github.com/atom/autocomplete-plus/issues/932) Please fix it.

**Comment by rsese** [comment] 2019-04-16 20:57
Thanks for contributing - our engineers can only prioritize a finite number of items so some issues won't get worked on for a while in some cases unfortunately. The team is however open to reviewing well-written pull requests to resolve this problem.

Because this is a duplicate of https://github.com/atom/autocomplete-plus/issues/932, we're closing in favor of that issue.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-16 20:57 UTC
