### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by quytelda** [atom/autocomplete-plus#969] opened 2018-05-12 01:39 UTC
Steps to reproduce:

1. Add `_` (underscore) to the list of Non Word Character in the settings for `atom/language-c`.
2. Open a C file
3. Type an `_` in the C file.

**Atom**: 1.26.1 x64
**Electron**: 1.8.4
**OS**: linux 4.16.8 (Arch Linux)
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.40.5

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:513

TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:513:66)
    at AutocompleteManager.getPrefix (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:493:37)
    at AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:25)
    at AutocompleteManager.requestNewSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:690:12)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:756:12)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1730:26)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:957:12)
    at TextEditor.transact (/usr/lib/atom/src/text-editor.js:1834:24)
    at mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:1381:19)
    at TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:3247:20)
    at TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:3218:36)
    at TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1380:17)
    at TextEditor.insertText (/usr/lib/atom/src/text-editor.js:1344:25)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/lib/atom/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.didTextInput (/usr/lib/atom/src/text-editor-component.js:1651:24)
```

### Commands

```
     -0:43.6.0 tree-view:toggle (atom-pane.pane.active)
     -0:34.9.0 application:reopen-project (div.tool-panel.tree-view)
     -0:29.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.2.3 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.8.0 
language-haskell 1.17.7 
```

**Comment by rsese** [comment] 2018-05-14 20:35
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/autocomplete-plus/issues/956 and the fix is in 1.27 (currently in beta).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 20:35 UTC
