### ISSUE TITLE
Autocomplete gives precedence to words ignoring characters before the dash

### ISSUE THREAD

**Issue by nicmosc** [atom/autocomplete-plus#942] opened 2018-01-06 16:44 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Looking at the following example:
![image](https://user-images.githubusercontent.com/16778318/34641671-dc978d60-f307-11e7-8a78-82b70ea6f2a5.png)

**Behavior:**
We would expect the first suggestion to be `flex-direction`, instead autocomplete ignores the dash and suggests `debug`. This was not the case until the last version. I cannot tell until which version this worked as I only noticed recently. However it isn't ideal as it is sort of a habit to expect `flex-d` to complete to `flex-direction`, and similarly with other cases:

![image](https://user-images.githubusercontent.com/16778318/34641698-5fb5b7b2-f308-11e7-90d6-8181698acd4a.png)

### Steps to Reproduce

Simply type CSS that includes dashes and where the characters following the dash could lead to more than 1 possible completion, as shown above. Examples where this does not happen:

![image](https://user-images.githubusercontent.com/16778318/34641734-e756b7b6-f308-11e7-802f-72fdb81d86d8.png)

This is because Atom does not have words that begin with `it` (at least in my case)

![image](https://user-images.githubusercontent.com/16778318/34641746-ff6419b6-f308-11e7-9950-e7a59aef39e1.png)

### Versions
This happens in versions:
- Atom: 1.23.2
- Mac OS High Sierra: 10.13.1

**Comment by AbdelrahmanHafez** [comment] 2018-02-23 09:28
Actually, the problem for me is that strings with dashes do not appear at all in suggestions.
Am I doing something wrong?
![screenshot_494](https://user-images.githubusercontent.com/19984935/36587093-ab4ddae8-188c-11e8-925b-01237a41e620.jpg)

**Comment by rsese** [comment] 2018-07-13 22:41
Thanks for reporting @nicmosc - this no longer seems to be the case?

![ac-hyphen](https://github-slack.s3.amazonaws.com/monosnap/untitled_2018-07-13_17-39-15.png)

The `review` snippet doesn't show up at all for me after typing `padding-r` (but is available if I type just `rev` for example).

This was on macOS 10.12.6 with Atom `1.29.0-beta1` in safe mode.

**Comment by nicmosc** [comment] 2018-07-14 12:08
@rsese the issue is described originally seems to be gone indeed!

However I've also found this to be a bit strange:
![image](https://user-images.githubusercontent.com/16778318/42724240-1ea13390-876f-11e8-9fd3-a1a5d851868a.png)

I would expect width to be the first suggestion after typing `wi` however atom highlights the `i` in `warning` instead. Is this expected behaviour?

- Atom 1.28.1
- Mac OS 10.13.5

**Comment by Aerijo** [comment] 2018-07-14 13:12
@nicmosc The `warning` snippet has priority 2, whereas CSS suggestions don't specify and default to a priority of 1.

This doesn't appear to be configurable, so I'm sure either a patch to the CSS provider, to give it a higher priority, or make it configurable would be welcomed.

**Comment by rsese** [comment] 2018-07-16 16:43
Thanks @Aerijo :+1:

@nicmosc since the reported issue is no longer reproducible, I'll go ahead and close this.

**Closed by rsese** 2018-07-16 16:43 UTC
Labels: more-information-needed
