### ISSUE TITLE
Non Ascii characters are not considered for word suggestions

### ISSUE THREAD

**Issue by AnotherJoSmith** [atom/autocomplete-plus#573] opened 2015-09-15 14:24 UTC
In this example I have the word `Sécurité` present in my document. However autocomplete suggests `curit`, which is not in the document. The expected behaviour here would be that the whole word `Sécurité` would be suggested by autocomplete.

<img width="345" alt="screen shot 2015-09-15 at 10 19 54 am" src="https://cloud.githubusercontent.com/assets/3300109/9879005/86010f66-5b93-11e5-9ca7-5acdb0261007.png">

**Comment by izuzak** [comment] 2015-09-15 14:27
I'm guessing this is a duplicate of https://github.com/atom/autocomplete-plus/issues/76, so closing in favor of that one. Let me know if I misunderstood your report, though :v:

**Closed by izuzak** 2015-09-15 14:27 UTC

**Comment by AnotherJoSmith** [comment] 2015-09-15 14:28
:+1:, didn't see that issue when scrolling through the issues
