### ISSUE TITLE
Hitting Enter on html attribute doesent make autocomplete.

### ISSUE THREAD

**Issue by mnquintana** [atom/autocomplete-plus#527] opened 2015-07-08 11:14 UTC
_From @abdelouahabb on July 7, 2015 22:6_

When I try to choose the html attribute, I have to click on it, and not hit Tab or Enter.

Other editors do that by just hitting Enter.

![sans titre](https://cloud.githubusercontent.com/assets/2527234/8558535/bb6ffac2-24fc-11e5-9a29-5064525502a8.png)

_Copied from original issue: atom/atom#7775_

**Comment by mnquintana** [comment] 2015-07-08 11:14
_From @thomasjo on July 8, 2015 7:14_

Are you able to reproduce this in safe mode? `atom --safe`
I'm reasonably sure one of your installed packages is interfering, possibly `emmet` if you have that installed.

In addition, after you toggle the *Keybinding Resolver*, what it shown when you press <kbd>enter</kbd> when the autocompletion list is active like in your screenshot?

**Comment by mnquintana** [comment] 2015-07-08 11:14
_From @batjko on July 8, 2015 8:55_

Works fine for me, using `Tab` and `Enter` (Win8, 64bit, v1.0.0):
![http://i.imgur.com/K231kxQ.gif](http://i.imgur.com/K231kxQ.gif)

**Comment by benogle** [comment] 2015-07-08 16:10
Also @abdelouahabb, if safe mode doesnt work, can you paste in the result of the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings)?

**Comment by abdelouahabb** [comment] 2015-07-08 17:22
@everyone `safe mode` worked, it seems that the problem is from `emmet` as @mnquintana said,

And since majority of users will install `emmet` can you please look how to solve it? maybe the `emmet` team should change the key binding?

**Comment by benogle** [comment] 2015-07-08 18:27
Can you file an issue on https://github.com/emmetio/emmet-atom ?

**Comment by benogle** [comment] 2015-07-08 18:27
Closing as this is an emmet issue.

**Closed by benogle** 2015-07-08 18:27 UTC
Labels: more-information-needed
