### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by capitalaslash** [atom/autocomplete-plus#722] opened 2016-05-20 10:22 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.29.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at AutocompleteManager.module.exports.AutocompleteManager.isCurrentFileBlackListed (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:623:23)
    at AutocompleteManager.isCurrentFileBlackListed (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:266:16)
    at /usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:16.8.0 core:copy (atom-text-editor.editor.is-focused.mini)
     -0:08.4.0 core:paste (atom-text-editor.editor.is-focused.mini)
 24x -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused.mini)
     -0:02.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused.mini)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused.mini)
     -0:02.5.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused.mini)
     -0:02.5.0 editor:newline (atom-text-editor.editor.is-focused.mini)
     -0:02.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "linter-cpplint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-moose, v0.20.0
build, v0.63.0
build-cmake, v0.4.0
build-make, v0.9.0
column-select, v0.2.0
gcc-make-run, v0.2.7
language-cmake, v0.1.4
language-docker, v1.1.6
language-gmsh, v0.1.0
language-latex, v0.6.1
language-moose, v0.17.0
language-qml, v1.0.0
linter, v1.11.4
linter-chktex, v1.3.0
linter-gcc, v0.6.14
linter-moose, v0.4.0
linter-python-pep8, v0.2.0
markdown-writer, v2.3.3
merge-conflicts, v1.4.2
terminal-plus, v0.14.5
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by muayyad-alsadi** [comment] 2016-06-06 12:01
maybe when we working on "new" unsaved file

**Comment by lee-dohm** [comment] 2016-06-07 17:08
@capitalaslash  Please include the output from `atom --version`, we suspect that this is caused by some Arch package managers building Atom in an unsupported way.

**Comment by vrutkovs** [comment] 2016-06-07 17:11
Happens on F23 with ```atom-1.7.4-4.git6bed3e5.fc23.x86_64``` from https://copr.fedorainfracloud.org/coprs/mosquito/atom/, ```--version``` output:
```
Atom    : 1.7.4
Electron: 1.2.0
Chrome  : 51.0.2704.63
Node    : 6.1.0
```

STR:
1. File - New Window

**Comment by muayyad-alsadi** [comment] 2016-06-07 18:23
@lee-dohm I'm using Fedora just like @vrutkovs and the bug is cased by calling basename on undefined. Please check my pull request.

**Comment by the-question** [comment] 2016-06-11 19:17
Still present on F23, with `atom-1.8.0-1.gitf89b273.fc23.x86_64` from `mosquito/atom` copr, and autocomplete-plus 2.29.2.
```bash
$ atom --version
Atom    : 1.8.0
Electron: 1.2.2
Chrome  : 51.0.2704.84
Node    : 6.1.0
```

STR:
1. New tab
2. Start typing

Waiting for PR #726 review and merge

**Comment by lee-dohm** [comment] 2016-06-11 19:35
Thanks everyone for supplying with the `--version` output. In each case, Atom has been built with an incompatible version of Electron. So I'm going to have to close this as `wontfix`. Thanks everyone for reporting the problem. You should encourage the package maintainers to use a supported version of Electron when packaging Atom.

**Closed by lee-dohm** 2016-06-11 19:35 UTC
Labels: more-information-needed

**Comment by the-question** [comment] 2016-06-12 23:15
To anyone landing here from Atom's _View issue_ link or a search engine, an issue is open at atom/atom#11967 about updating Atom's Electron version.

**Comment by muayyad-alsadi** [comment] 2016-06-14 12:23
if we don't want to add `if` statement, we can just ` || "" `
