### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/kritikarai/Library/Application S...

### ISSUE THREAD

**Issue by krai20** [atom/autocomplete-plus#580] opened 2015-09-21 04:58 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.19.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
  at toRealPath (module.js:108:13)
  at tryFile (module.js:104:22)
  at tryPackage (module.js:92:10)
  at Function.Module._findPath (module.js:155:20)
  at Module._resolveFilename (module.js:332:25)
  at Function.Module._resolveFilename (/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at AutocompleteManager.module.exports.AutocompleteManager.isCurrentFileBlackListed (/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:576:21)
  at AutocompleteManager.isCurrentFileBlackListed (/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:223:16)
  at /Users/kritikarai/Library/Application Support/com.github.atom.ShipIt/update.U12i9Ky/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -1:32.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:32.6.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -1:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
  9x -1:17.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:16.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  6x -1:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
 17x -1:12 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:10.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:06.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -1:01.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:45.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:43.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:42.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by krai20** [comment] 2015-09-21 04:59
started happening after I installed pylinter.

**Comment by 50Wliu** [comment] 2015-11-13 21:27
Closing as a duplicate of atom/atom#7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-13 21:27 UTC
Labels: uncaught-exception
