### ISSUE TITLE
Autocomplete not finish the suggestion

### ISSUE THREAD

**Issue by thovo** [atom/autocomplete-plus#708] opened 2016-04-15 08:22 UTC
Hi,

The autocomplete didn't finish when I confirmed the word by enter or tab+enter. After confirming the selection, it left with doing
![atom](https://cloud.githubusercontent.com/assets/1543066/14555616/e32fe326-02f3-11e6-9b48-1666128bec1c.png)
 nothing.
![atom2](https://cloud.githubusercontent.com/assets/1543066/14555637/f4a964b0-02f3-11e6-8a7d-619d476e208c.png)

I tried to reinstall Atom or toggle enable autocomplete plus or change the keymap settings but it didn't work either.
The keymap:
![atom3](https://cloud.githubusercontent.com/assets/1543066/14555642/fc56e322-02f3-11e6-89df-36275f00a420.png)

**Comment by yardfarmer** [comment] 2016-04-18 02:18
same to me!

**Comment by jensfranke** [comment] 2016-04-18 05:56
same to me

**Comment by thovo** [comment] 2016-04-18 08:47
I found I didn't reinstall correctly, I needed to manually remove every Atom packages, I mean everything relate to Atom and reinstall it. It worked normally now but this bus was still very strange. A few days before it happened, it worked normally without any problem. I am not sure this bug happened when I updated my Windows.

**Comment by bmatto** [comment] 2016-04-21 14:02
I'm seeing this issue as well.

**Comment by lee-dohm** [comment] 2016-04-21 15:24
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by bmatto** [comment] 2016-04-21 15:31
@lee-dohm Emmet was the culprit.

**Comment by lee-dohm** [comment] 2016-04-21 16:51
Thanks @bmatto :grinning:

**Comment by thovo** [comment] 2016-04-22 07:29
Atom 1.7.2
Windows 7 64 bit
I had Emmet installed and removed when I need
Can't reproduce the issue due to I already installed a new one but in my new Atom, I didn't install Emmet yet, could you please investigate?

**Comment by lee-dohm** [comment] 2016-04-22 20:44
@thovo I'm not sure what you're asking me to investigate? We don't support the Emmet package. So if it is causing this problem for you, you'll have to follow up with the Emmet maintainers.

**Comment by thovo** [comment] 2016-04-23 13:35
I just want to know what is the root cause of the problem? Probaly Emmet but after checking several package, I found some small issue like the color of angular ui tab is not recognized as `uib-accordion`, it is half-style only. Probaly the problem come from other package like angular ui or bootstrap.

**Comment by lee-dohm** [comment] 2016-04-23 16:01
@thovo The root cause of the problem is that Emmet takes over the handling of certain keybindings in a way that messes up standard Atom functions, like autocomplete-plus. So if you have Emmet installed, you can either uninstall Emmet or follow up with the Emmet maintainers for a fix. Atom doesn't have any support for Angular out of the box either. If you are having problems with a package that offers Angular support, you can follow up with the maintainers of that package.

The FAQ on the official Atom discussion forum has information on how to contact the maintainers of any Atom package:

https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581

Since you can't reproduce the issue anymore without Emmet, I'm going to close the Issue. If I've misunderstood the situation or you can reproduce the issue again without Emmet installed, please feel free to reopen it.

**Closed by lee-dohm** 2016-04-23 16:01 UTC
Labels: more-information-needed, needs-reproduction
