### ISSUE TITLE
Sass variables flood the list

### ISSUE THREAD

**Issue by smlombardi** [atom/autocomplete-plus#469] opened 2015-05-18 16:16 UTC
However, in sass files in my project the menu is swamped with Sass variables...

![screen shot 2015-05-18 at 11 40 55 am](https://cloud.githubusercontent.com/assets/835148/7684882/aa723932-fd57-11e4-9a3b-7ebdb4332ca4.png)

I'd prefer to have "regular" css suggestions first, such as "background-color"

Can the order be controlled, or can I disable sass variable suggestion?

**Comment by benogle** [comment] 2015-05-18 17:35
This is strange for a few reasons: there are `$` at the beginning of the strings, they are not tagged with the variable type, and they are matching in the middle of the symbol. 

Can you do 2 things for me: 

1. paste in results of run `apm list`
1. Paste in autocomplete-plus config

**Comment by smlombardi** [comment] 2015-05-18 18:00
Here is apm list: http://cl.ly/text/3v003X2r2s2E/apm%20list.txt

where do i find the config?

**Comment by benogle** [comment] 2015-05-18 18:03
Open the command palette (cmd-shift-p) and type `open config`. There might (if you have changed settings) be an `autocomplete-plus` key. 

Here are the packages:

```
â”œâ”€â”€ 2-dark-syntax@0.1.1
â”œâ”€â”€ SFTP-deployment@1.0.0
â”œâ”€â”€ alignment@1.1.5
â”œâ”€â”€ angularjs@0.1.0
â”œâ”€â”€ atom-beautify@0.27.1
â”œâ”€â”€ atom-bootstrap3@1.2.2
â”œâ”€â”€ atom-color-highlight@3.0.9
â”œâ”€â”€ autocomplete-paths@1.0.2
â”œâ”€â”€ autoprefixer@2.2.3
â”œâ”€â”€ color-picker@1.7.0
â”œâ”€â”€ csscomb@0.1.2
â”œâ”€â”€ darkula-syntax@0.3.0
â”œâ”€â”€ domani@0.0.0
â”œâ”€â”€ emmet@2.3.9
â”œâ”€â”€ file-icons@1.5.5
â”œâ”€â”€ flat-syntax@0.2.0
â”œâ”€â”€ gruvbox-mellow@0.2.0
â”œâ”€â”€ gulp-helper@2.0.0
â”œâ”€â”€ inspired-github@0.5.2
â”œâ”€â”€ isotope-light-ui@2.1.0
â”œâ”€â”€ isotope-ui@2.2.1
â”œâ”€â”€ jscs-fixer@0.5.1
â”œâ”€â”€ kuroir-atom@1.0.3
â”œâ”€â”€ linter@0.12.2
â”œâ”€â”€ linter-csslint@0.0.12
â”œâ”€â”€ linter-jscs@1.11.0
â”œâ”€â”€ linter-jshint@0.1.4
â”œâ”€â”€ linter-jsonlint@0.1.3
â”œâ”€â”€ linter-scss-lint@0.0.14
â”œâ”€â”€ neutron-syntax@0.6.2
â”œâ”€â”€ oceanic-next-syntax@0.1.1
â”œâ”€â”€ primer.light@0.0.0
â”œâ”€â”€ project-manager@1.15.5
â”œâ”€â”€ project-palette-finder@2.4.17
â”œâ”€â”€ selection-counter@0.1.1
â”œâ”€â”€ solarized-light-syntax@0.21.0
â”œâ”€â”€ sort-lines@0.11.0
â”œâ”€â”€ tag@0.2.3
â”œâ”€â”€ tesla-atom@0.2.0
â””â”€â”€ tomorrow@1.0.0
```

**Comment by smlombardi** [comment] 2015-05-18 18:09
ok, just 
````
  "autocomplete-plus":
    confirmCompletion: "enter"
`````

**Comment by smlombardi** [comment] 2015-05-20 10:12
Any info on this?

**Comment by joefitzgerald** [comment] 2015-05-20 12:11
@smlombardi: are you using the FuzzyProvider as the default provider by any chance?

**Comment by smlombardi** [comment] 2015-05-20 12:34
Strict is un-checked, so I suppose  I am.

**Comment by smlombardi** [comment] 2015-05-23 17:49
This happens with Strict both on or off.

**Comment by smlombardi** [comment] 2015-06-03 13:09
Is there any progress on this?  If nothing else, I'd like to **exclude** my variables from Autocomplete.

**Comment by benogle** [comment] 2015-07-08 21:49
I am not able to reproduce this. Is it still an issue? I also get the css suggestions at the top of the list. I bet another package is causing this. Though none of them jump out at me as causing this. Did you try `atom --safe`?

![screen shot 2015-07-08 at 2 47 43 pm](https://cloud.githubusercontent.com/assets/69169/8583189/8511512c-2580-11e5-8b07-e8a32f66064c.png)

**Comment by benogle** [comment] 2015-07-21 23:44
Closing this as I think it's caused by some package.

**Closed by benogle** 2015-07-21 23:44 UTC
Labels: atom, more-information-needed, question

**Comment by smlombardi** [comment] 2015-07-21 23:47
It no longer is an Issue.
