### ISSUE TITLE
Prefix copied twice

### ISSUE THREAD

**Issue by jeancroy** [atom/autocomplete-plus#560] opened 2015-08-11 03:29 UTC
![Screen](https://i.gyazo.com/03b1a060d5887b81fbc6814e47a4e0ce.gif)
(using `atom --safe`, version 1.0.5)

What happens in the screenshot ?
 1.  Type `console`, keyword get recognized -> yellow
 2.  Type `.lo`, auto-complete window appears
 3.  Press `<tab>` to accept first. (Can also reproduce with `<enter>` or `<click>`)

Result is  `console.console.log();`

Repeat Undos ( ctrl-z )
- `console.log`
- `console.lo`
- `console.`
- `console`
- ` `

First undo is interesting because by itself it's a successful auto-complete.
Doesn't have the extra `();` to the end, but also do not duplicate prefix `console.`
Maybe both auto-complete and snippet try to complete console.log() ?

**Comment by benogle** [comment] 2015-08-11 17:26
Autocomplete in its default form is not context aware, so the `log` in the suggestion list is not a response to you typing `console.`. The item in the list you're expanding is a global _snippet_ (indicated by the green arrow). The idea with this snippet is that you just type `log` then it expands to `console.log();`. 

Closing as this is not a bug.

**Closed by benogle** 2015-08-11 17:26 UTC

**Comment by jeancroy** [comment] 2015-08-11 17:33
What it is if not a bug ? Certainly not an expected behavior.
Should I report as a bug in snippet instead ?

The thing is I did nothing to ask a snippet to be inserted.
Accepting completion of "auto-complete" then trigger the snippet. Even using mouse.

**Comment by benogle** [comment] 2015-08-11 17:37
> Certainly not an expected behavior.

Well, in this case, it is expected behavior. When you expand the `log` snippet in js, it expands to `console.log();` all the time, no matter what prefixes `log`. 

> Accepting completion of "auto-complete" then trigger the snippet.

This accepting of a snippet from autocomplete does trigger the snippet to expand. 

If you want something more context aware, try using the [ternjs](https://atom.io/packages/atom-ternjs) package.

**Comment by jeancroy** [comment] 2015-08-11 17:47
Ok. Understand better the situation. There's still some UI confusion along the line of:

- Snippet entry really looks like auto-complete. (Green arrow symbol looks like a generic "insert", no text explanation, tool-tip on mouse over or anything)
- Snippet entry don't explain what will be inserted (content of snippet "console.log();" is not hinted in the UI, only show snippet by its name)
- Snippet don't interpolate with what is already there.

However I understand it's not a bug of autocomplete. Thank you.
