### ISSUE TITLE
Check for null in configSuggestionsToSubsequenceMatches

### ISSUE THREAD

**Issue by Arcanemagus** [atom/autocomplete-plus#965] opened 2018-04-12 03:19 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The following code fails to check the return value for `findWordsWithSubsequence` and assumes it returned a list of suggestions:
https://github.com/atom/autocomplete-plus/blob/b8e2223e973ac3253e2ffd47fccb59e52336d955/lib/subsequence-provider.js#L100-L105

This can lead to the following error being thrown:
```
Cannot read property 'length' of null; stack: TypeError: Cannot read property 'length' of null
    at configSuggestionsBuffer.findWordsWithSubsequence.then.matches (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:123:40)
```

### Steps to Reproduce

1. Trigger `SubsequenceProvider::getSuggestions` fast enough that the [call to `configSuggestionsToSubsequenceMatches`](https://github.com/atom/autocomplete-plus/blob/b8e2223e973ac3253e2ffd47fccb59e52336d955/lib/subsequence-provider.js#L168) can't complete?

**Expected behavior:** [What you expect to happen]

No error.

**Actual behavior:** [What actually happens]

An error.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Unknown.

### Versions

It's _possible_ in the code of `autocomplete-plus@2.40.6`, but reproduction steps to test Atom versions are unknown.

### Additional Information

Originally reported by @wanderley in https://github.com/atom/autocomplete-plus/pull/921#issuecomment-380608223.

**Comment by wanderley** [comment] 2018-04-12 03:48
Atom version: 1.25.1

I work in Nuclide Team and I found this issue when checking some error logs.

**Comment by Ben3eeE** [comment] 2018-04-18 20:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/autocomplete-plus/issues/948. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-04-18 20:05 UTC
