### ISSUE TITLE
Cannot read property 'replace' of undefined in certain filetypes

### ISSUE THREAD

**Issue by tylerFowler** [atom/autocomplete-plus#956] opened 2018-02-17 00:32 UTC
*Edit by @rsese to add repro steps*

1. Start Atom in safe mode `atom --safe`
2. Add `_` to `Settings > Editor > Non Word Characters`
3. Create a new file
4. Start typing in the new file

macOS 10.12.6 and Atom 1.25.

---

I find that in certain file types I get this exception thrown (Atom Beta). So far I've found it reliably does it in git commit message types (invoked by git-plus) and in Go files, but have not seen it with the same version in JS or Java files. It tends to keep throwing this error over and over as I type.

Worth noting this error was definitely *not* present until the latest Beta update, which included autocomplete-plus version 2.40.2

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527

TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
```

### Commands

```
  2x -0:09.1.0 core:move-down (input.hidden-input)
     -0:07.3.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:06.6.0 core:backspace (input.hidden-input)
     -0:05.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:04.3.0 core:move-up (input.hidden-input)
```

### Non-Core Packages
Was able to reproduce in safe mode

**Comment by tuomashatakka** [comment] 2018-02-26 15:59
I've noticed that this error is not raised when the `language-babel` package is disabled. I can't tell if it's caused by the language-babel, but I think it would be helpful to post this issue to its issues as well :--) 

Third time's the charm.

**Comment by tylerFowler** [comment] 2018-02-27 17:20
This is kind of weird but after the latest update to Atom my config was somehow completely blown away and now I'm no longer getting this error? Will close for now and reopen if I'm able to reproduce again.. And if it does crop up again I'll try disabling language-babel thanks for the tip @tuomashatakka

**Comment by iagoqo** [comment] 2018-03-14 13:50
I'm also on atom beta and have the same issue on plain text files, the version I'm using is `1.25.0-beta3`.

It's not a babel issue for me as it also happens on safe mode.

[Enter steps to reproduce:]

1. Open atom in safe mode
2. It opens with an empty plain text editor
3. Type anything
4. Error apppears

**Atom**: 1.25.0-beta3 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\ProgramData\iagoqo\atom\app-1.25.0-beta3\resources\app\node_modules\autocomplete-plus\lib\autocomplete-manager.js:527

TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (C:/ProgramData/iaaggooqqoo/atom/app-1.25.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
    at AutocompleteManager.requestNewSuggestions (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:3252:26)
    at TextEditor.mergeIntersectingSelections (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (C:/ProgramData/iagoqo/atom/app-1.25.0-beta3/resources/app/src/text-editor-component.js:1654:30)
```

### Commands

```
  2x -1:45.3.0 editor:delete-to-previous-word-boundary (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-03-15 21:05
@iagoqo have you tried clearing saved state (make sure to save any unsaved data first)?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by edrubin** [comment] 2018-03-16 14:36
I have the same issue only for R files. Unfortunately, clearing the saved state didn't help.

**Comment by BojanOro** [comment] 2018-03-16 15:07
I too have the same issue for at least Ruby and plain text files. HTML works fine.

**Comment by rsese** [comment] 2018-03-16 21:05
@edrubin @BojanOro is this in safe mode as well?

**Comment by BojanOro** [comment] 2018-03-16 21:23
@rsese indeed.

Atom    : 1.25.0
Electron: 1.7.11
OS: MacOS 10.13.1

Stack Trace:
```
TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3252:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

**Comment by rsese** [comment] 2018-03-16 22:04
Do you have steps to reproduce so we can give it a try @BojanOro?

**Comment by BojanOro** [comment] 2018-03-16 22:06
1) Open a new file
2) Start typing. Literally a single character will throw an exception.

**Comment by Aerijo** [comment] 2018-03-16 23:29
@BojanOro I cannot reproduce by following those steps. 

Is there anything more specific you can give, such as what config settings you have for `autocomplete-plus`? Additionally, check for scope specific settings under each language.

**Comment by drorata** [comment] 2018-03-19 08:00
I have the same issue:

```
/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527
Hide Stack Trace
TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3252:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

I have `Python Executable Paths` and `Extra Paths For Packages` set.

**Comment by Arcanemagus** [comment] 2018-03-19 17:08
@drorata Are you able to provide steps to reproduce this? So far the suggested steps of:
1. Open an editor
2. Type something

Haven't been able to be reproduced by anyone, so there must be something missing from them.

Can somebody who is experiencing this try [Resetting to Factory Defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) temporarily to see if they still see this on a clean profile?

**Comment by BojanOro** [comment] 2018-03-19 17:17
I apologize for the late reply...

I've reset to factory defaults and the issues goes away for me. I have done very little customization previously so I'm not entirely sure what was reset that made autocomplete work for me. When I have some time I'll look through my previous config and see if I can find the root cause.

**Comment by Arcanemagus** [comment] 2018-03-19 17:31
It's likely that any relevant difference would be in the `config.cson`, but as we haven't been able to replicate this I'm just guessing 😉. I'm glad to hear that that worked for you!

**Comment by rsese** [comment] 2018-03-19 17:44
For other folks reporting the error, can you also try temporarily resetting to factory defaults and confirm if the error clears up for you?  It might be interesting to see your `config.cson` files too.

**Comment by BojanOro** [comment] 2018-03-19 17:45
Steps to replicate:

1. Edit Editor > Non Word Characters - add an underscore _ to the end of the string (ie `/\()"':,.;<>~!@#$%^&*|+=[]{}`?-…_`)
2. Attempt to type

**Comment by Arcanemagus** [comment] 2018-03-19 17:50
I can confirm that adding `_` to the Non-Word characters list causes this, thanks for finding that @BojanOro!

**Comment by tylerFowler** [comment] 2018-03-19 20:11
Glad to see this one gained some traction.. sort of forgot about it after it was "fixed" for me, thanks @Arcanemagus for reopening.

**Comment by BojanOro** [comment] 2018-03-20 03:33
I think I've narrowed down the source of the problem, but I've never actually worked with Atom's packages so I'm hesitant to fix it myself; instead I hope that I can make somebody else save a few minutes of time tracking this down.

In `get-additional-word-characters.js`  when you do _not_ have `_` as a non-word character the `result` returned is `"undefined_"` (as in, a string). Adding `_` as a non-word character means the `_` is no longer concatenated and `result` is returned as `undefined` (as in, undefined). Obviously, `replace` in `AutocompleteManager.getWordCharacterRegex` will not work on undefined. 

Checking if `result` is undefined and returning an empty string if so fixes the problem, but I don't know if I'm missing some bigger picture item here and the problem is actually something else. Perhaps somebody else could actually implement a change?

**Comment by drorata** [comment] 2018-03-20 05:19
@BojanOro I have no experience as well, but this sounds very reasonable. I guess it is related to [this discussion](https://discuss.atom.io/t/unexpected-completion-with-tab-in-presence-of-underscore/52256) as well.

**Comment by anherrera** [comment] 2018-03-28 02:43
I also have _ configured as a non-word character and I am experiencing this issue.

Version 1.25.0.
OSX 10.12.6

**Comment by NathanRSmith** [comment] 2018-03-30 20:28
Issue occurs for https://atom.io/packages/language-restructuredtext with `_` in non-word character list.
#17047

**Comment by code-warrior** [comment] 2018-04-02 14:03
I can also confirm that removing the underscore character (`_`) in the value to the `nonWordCharacters` property in `config.cson` fixes this issue.

**Comment by AlexWayfer** [comment] 2018-04-02 14:07
> I can also confirm that removing the underscore character (_) in the value to the nonWordCharacters property in config.cson fixes this issue.

It isn't fix, it's work-around. Issue should be fixed normally.

**Comment by iagoqo** [comment] 2018-04-04 16:39
I can confirm that removing `_` from `nonWordCharacters` makes the issue go away on JSON and Plain Text files.

I'd like to add that I have it set on Javascript and HTML files but the issue doesn't happen on those.

**Comment by tylerFowler** [comment] 2018-04-04 18:28
I also removed `_` from `nonWordCharacters` and can confirm it fixes git commit messages and Java files.

**Closed** 2018-04-09 20:15 UTC
Labels: bug, triaged

**Comment by serialhex** [comment] 2018-04-10 17:33
I have the same issue Atom 1.25.1 & autocomplete-plus 2.40.2.  Having `_` in my Non Word Characters list makes it explode for *any* kind of file I use (VBS is most recent, and it may not happen for Plain Text, but any code).

**Comment by AlexWayfer** [comment] 2018-04-10 17:48
@serialhex Fixed in #961, as written above. It's included in `autocomplete-plus 2.40.6`.

(It's very sad that we can't update `autocomplete-plus` regardless of Atom version)

**Comment by drorata** [comment] 2018-04-24 13:18
Is there a way to manually update the package and have this fix?

**Comment by drorata** [comment] 2018-04-24 13:27
Thanks for the clarification. I thought "we" meant that there's no way for this update to be "pushed". It was not clear that there's no way to manually "pull" the update.

**Comment by AlexWayfer** [comment] 2018-04-24 13:31
No, I'm not team-member, I wrote "we" as "users".

Probably, there is a way to install this package _really_ manually, via package source core or something like that, but I don't advise doing this.

**Comment by Aerijo** [comment] 2018-04-24 13:58
To install any version, clone it and run the command `apm install` from the package root folder (running from outside this with a path will raise a deprecation warning, because it _is_ a bad idea to do this without reason). Then run `apm link` from the same place and reload Atom.

**Comment by Arcanemagus** [comment] 2018-04-25 01:47
Instructions are in the [Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/#hacking-on-packages) for running development versions of the packages, the simpler method is to just run the beta if your desired change is in that 😉.

**Comment by Aerijo** [comment] 2018-04-25 01:50
@Arcanemagus OK, I didn't realise it was in beta.

**Comment by AlexWayfer** [comment] 2018-05-02 09:24
> I believe this is not the beta version (?)

This is not any version of 1.27:

> Wait for Atom 1.27, or use beta version.
