### ISSUE TITLE
Glitches when the suggestions are close to editor boundaries

### ISSUE THREAD

**Issue by jeremyfa** [atom/autocomplete-plus#738] opened 2016-06-29 10:51 UTC
See the capture below, pretty often, when typing next to editor boundaries, the box is changing position all the time/flickering. Sometimes I don't even have to move/scroll anything and the box will never settle to a fixed position. I am suspecting this is an issue with atom's marker decoration, but still think it's important to file an issue here as there is where the concrete problem happens.

I checked that there is no custom style that could cause the problem, but apparently not.

Anybody having the same issue?

![atom-glitch](https://cloud.githubusercontent.com/assets/164094/16449400/a34ba8c8-3df7-11e6-9d8f-30b192886fa4.gif)

**Comment by Ben3eeE** [comment] 2016-10-14 05:48
Closing as a duplicate of https://github.com/atom/atom/issues/8295 which was closed via https://github.com/atom/atom/pull/12977

**Closed by Ben3eeE** 2016-10-14 05:48 UTC
