### ISSUE TITLE
Why the auto suggestion hasn't icon on left？

### ISSUE THREAD

**Issue by YYYYCY** [atom/autocomplete-plus#1021] opened 2019-01-31 08:02 UTC
Atom: 1.34.0
autocomplete-plus: 2.42.0
Mac: macOS Mojave 10.14.2

![image](https://user-images.githubusercontent.com/15774890/52040189-9d2cc580-2571-11e9-88f0-8d23f65ae828.png)

**Comment by Aerijo** [comment] 2019-01-31 08:10
Duplicate of https://github.com/atom/autocomplete-snippets/issues/99

I'll put in a PR

**Closed by Aerijo** 2019-01-31 08:10 UTC
