### ISSUE TITLE
Completion window shown/hidden behind other panes when shown at bottom of pane.

### ISSUE THREAD

**Issue by peterhal** [atom/autocomplete-plus#584] opened 2015-09-25 21:43 UTC
Repro 1:

Open a file.
Open the Search with cmd-shift-F
Click to file
Show auto-complete within 1-3 lines of the bottom of the editor pane.

Actual:

![screenshot 2015-09-25 14 35 45](https://cloud.githubusercontent.com/assets/875648/10112824/36fe5984-6393-11e5-8c89-515a9c201f39.png)

Expect:

Autocomplete results should show above the cursor if they cannot fit below the cursor.

Repro 2:

Open 2 files
Split Horizontally
Select the top pane
Show autocomplete within 1 -3 lines of the bottom of the editor Pane

Actual:

Note that part of the autocomplete results are obscured by the lower row of editor tabs.

![screenshot 2015-09-25 14 37 25](https://cloud.githubusercontent.com/assets/875648/10112857/9c879130-6393-11e5-8520-d64f5378e565.png)

Expect:

Autocomplete results should either show over top of the editor tabs, or above the cursor.

**Comment by benogle** [comment] 2015-10-02 18:21
What version of atom? What theme? Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? This works for me on latest master with one theme:

![screen shot 2015-10-02 at 11 19 25 am](https://cloud.githubusercontent.com/assets/69169/10254315/a898488e-68f7-11e5-9bb9-3b2f2a9ed8b8.png)

![screen shot 2015-10-02 at 11 20 18 am](https://cloud.githubusercontent.com/assets/69169/10254316/a8985ebe-68f7-11e5-920e-c1d3690ac846.png)

**Comment by benogle** [comment] 2015-10-12 23:16
Closing as no more information has been provided. My assumption is that it is an issue with the theme. Try with one of the builtin themes and let me know if the issue is still there.

**Closed by benogle** 2015-10-12 23:16 UTC
Labels: more-information-needed

**Comment by johnislarry** [comment] 2016-04-25 17:39
Atom 1.6.2
one light theme for both UI and syntax
autocomplete-plus is at 2.25.0

![screenshot 2016-04-25 10 37 08](https://cloud.githubusercontent.com/assets/1064522/14792978/bb343cec-0ad1-11e6-9be6-742109906507.png)
