### ISSUE TITLE
snippets get disappeared after keep typing

### ISSUE THREAD

**Issue by dragonxlwang** [atom/autocomplete-plus#692] opened 2016-03-24 05:15 UTC
This is a problem when using atom-you-complete-me. I talked to the author and thinks it might be a limitation of current autocomplete-plus...

Here's the [issue](https://github.com/Qusic/atom-youcompleteme/issues/53).

The symptoms are that after keep typing the keyword of snippet, it get disappeared. This is related to priority settings.

Can we allow both autocompletion and snippet coexist in the pop up menu?

Thanks,

**Comment by lee-dohm** [comment] 2016-04-20 07:14
We do allow suggestions from multiple providers to appear in the autocomplete popup, so I'm not sure what the issue is here?

**Comment by Ben3eeE** [comment] 2016-12-19 11:43
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/autocomplete-plus/issues/692#issuecomment-212292939. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-19 11:43 UTC
Labels: more-information-needed
