### ISSUE TITLE
Auto complete panel disappears immediately after typing second word

### ISSUE THREAD

**Issue by preco21** [atom/autocomplete-plus#861] opened 2017-06-19 09:15 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When trying to use snippets, autocomplete panel disappears immediately after typing second word, even if the words are matching to the snippet.

See blow:

![kapture 2017-06-19 at 18 09 34 mp4](https://user-images.githubusercontent.com/4936201/27277882-bb57a4f4-551a-11e7-9466-64889ad526aa.gif)

### Steps to Reproduce

1. Open Atom
2. Create new document
3. Type something that matches any auto complete snippets.

**Expected behavior:** Auto complete panel keep showing even after typing the second word.

**Actual behavior:** Auto complete panel disappears immediately right after typing the second word.

**Reproduces how often:** Every time you trying to use auto complete snippets

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

`macOS Sierra 10.12.5`

**Comment by rsese** [comment] 2017-06-19 10:09
Thanks for taking the time to contribute!

We noticed that this seems like a duplicate of https://github.com/atom/autocomplete-plus/issues/850. If I mis-understood please let me know but otherwise, you may want to subscribe there for updates.  The issue body also mentions a config setting that you can adjust that may workaround the problem

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-19 10:09 UTC
