### ISSUE TITLE
Complete suggestions as they are selected

### ISSUE THREAD

**Issue by geoffharcourt** [atom/autocomplete-plus#240] opened 2015-02-04 14:39 UTC
One of the things I love about Vim's autocompletion is that if I select a completion option and then just keep typing that it's not necessary to perform the "activate" action to get your suggestion populated in the document. As you scroll through the options, the editor is already replacing the text in the editor pane. Canceling restores your word to wherever it was before you started pressing tab/up-down/ctrl-p, etc.

I'm sure some users would not like this behavior, but it would be awesome if it could be turned on and off with a checkbox in the package settings.

**Comment by evindor** [comment] 2015-02-26 21:26
I have a solution [here](https://github.com/evindor/autocomplete-plus/commit/2de931d6204843618094075cda828e619a5ac55f). With `Confirm Selection By Typing` option set to true your selection will be confirmed if you type anything that doesn't match a binding (read as "just continue typing"). You still have to press `Enter` or whatever key you have for this to confirm the first suggestion that's selected automatically.

I'd be grateful for help with tests to make a pull request out of it.

**Comment by evindor** [comment] 2015-02-26 21:29
It doesn't behave exactly like YouCompleteMe, inserting suggestions into document as you select them, but offers nearly the same experience. And it was much less effort to implement over the current system.

**Comment by evindor** [comment] 2015-02-26 21:43
Also it's possible to easily implement "nothing selected" behavior (you'll need to cycle (tab/down/ctrl-n/whatever) even to the first match, then you can continue typing to insert that match).

Then the only difference with YCM will be that with YCM you see your match in the document before you continue typing, mine solution renders it after.

**Comment by gglanzani** [comment] 2015-05-07 08:37
Is this going to be merged, with an option or something?

**Comment by dlo** [comment] 2015-06-27 18:10
I'm really happy I searched through the issues before posting anything, but I came here to request this exactly.

**Comment by evindor** [comment] 2015-06-28 01:21
I've merged fresh master to that PR, but there is a bug with `-1` index of selected element. A bit tough to hack with the new code, but manageable. Thing is it's been a while and I got familiar with the default selection style. However, if we get :+1: from owners on merging this as an off by default option ("YCM selection style") I'm happy to help to reanimate that PR.

**Comment by dlo** [comment] 2015-06-28 02:28
Woot! Thanks @evindor! Really hoping this can be merged in :)

**Comment by benogle** [comment] 2015-06-30 22:35
At this time, I am inclined to keep the existing behavior so that typing always refines the suggestion list.

**Comment by dlo** [comment] 2015-06-30 23:00
@benogle As far as I can tell, with this proposed behavior, typing would still refine the suggestion list, with the difference being that the top suggestion would already be filled in.

**Comment by benogle** [comment] 2015-06-30 23:06
Though: 

* If you move the selection in the list (from no selection), then type, it would complete it
* If you type, and the first suggestion is the right one, you need to hit `down, enter` or `down, type something`

I'd rather just keep things simple and leave it as it is currently.

**Comment by phorust** [comment] 2015-07-02 02:27
This improves autocompletion workflow because there's no need for a "complete this" keystroke. Typing refines the suggestion list until the user sees what they want in the suggestion list. Then, from no selection the user presses `down`. When the user reaches the right selection, they continue typing, and their selection is inserted into the editor as well as the character they just typed.

I think having this as a default option off would still keep things simple. Having YCM-like completion would be a vast improvement.

**Comment by gglanzani** [comment] 2015-07-02 08:13
I agree wholeheartedly with @phorust

**Comment by evindor** [comment] 2015-07-22 13:47
Well, we have 5 people who want this feature just in this issue. I bet there are hundreds more if you ask in vim-mode repo. @benogle what's your concern in implementing it as an option which is turned off by default?

**Comment by evindor** [comment] 2015-07-22 13:49
If you are concerned about additional logic we can refactor it and hide it somewhere. I understand your concern about maintaining a bit more logic after the merge, but it's not too complicated logic. And it can be refactored and hidden nicely.

**Comment by evindor** [comment] 2015-07-22 13:51
Thing is that what we are discussing here is the default behavior in vim's YCM and a ton of vimmers are used to it. Would be nice to have the same in atom.

**Comment by dlo** [comment] 2015-07-22 13:54
Yep, agreed. @evindor nailed it. The fact that this feature isn't implemented is blocking my ability to switch. I'm just too used to the Vim way.

**Comment by benogle** [comment] 2015-07-22 16:12
My reluctance comes mainly from the fact that it's not better/faster, just different. And for this extra, different behavior, it adds complexity to the code, and it's yet another behavior the core team (or I) need to support.

> This improves autocompletion workflow because there's no need for a "complete this" keystroke.

I disagree. 

In the most common case where what you want is the first item, both behaviors complete in one keystroke. In this behavior, you hit `down` and keep typing. In the current behavior, you hit `enter` and keep typing. 

If you have to arrow through the list, both behaviors are n + 1 keystrokes. In this behavior, you hit `down`  n + 1 times (item 0 is not selected!). In the current behavior, you hit `down` n times (0 is already selected!) then `enter`.

We've chosen this behavior because it is the most common behavior out there: sublime, v studio, xcode, etc.

Additionally, the PR

* does not have any tests
* does not take into account that  `confirmCompletion` is no longer needed, and still binds the confirm keymaps
* is likely missing edge cases that will be created as issues, and someone will need to fix

**Comment by evindor** [comment] 2015-07-22 16:54
> In the most common case where what you want is the first item

I doubt that it's the most common case _for everyone_, someone prefers to narrow down the list (thanks to fuzzy search it's fairly simple, but sometimes you need to think "what do i need to type next to get the item I want on top of the list?"). Others spot the item before it is close to the first place, and prefer to cycle with tab/arrows.

> Additionally, the PR ...

Sure, it is not intended to be merged in its current state, when I saw the general disagreement with this feature from the core team I stopped spending time on the PR, what's the point if it won't get merged. If we finally decide on the fact that this feature could be merged, tests and proper refactoring are to come.

re additional logic to maintain, there are just a couple changes:
- default index is `0` for default style and `-1` for YCM style
- we have to catch and pass around the confirming `keystroke` to insert it in the editor

I bet we can implement these without any noticeable additional maintenance work for the core team.

> it's not better/faster, just different

Exactly! And there are people out there who want it different! For someone (@dlo) it's even blocking a switch!
There is one edge case where YCM style wins: at the end of the line. With the current style you may still have autocomplete visible and if you press `enter` you will get an unwanted completion and no newline, so you have to press `escape` first. With YCM style you just hit `enter`.

**Comment by evindor** [comment] 2015-07-22 17:14
@benogle I have a suggestion/compromise:
1. We discard #296 
2. Instead we expose some of the autocomplete+ functions as services — confirm, set default index, move up/down
3. All the logic for this feature goes to a separate plugin, something like "autocomplete-plus-ycm-style" which is its author's own headache.

**Comment by jeancroy** [comment] 2015-07-22 18:16
I'm not sure I understand the full behavior of YCM.

but having:
`obj.prp.me(`

complete to 
`object.property.method()`

would be nice. Aka the full range of boundary char could be used to confirm a selection.

**Comment by kepbod** [comment] 2015-08-18 14:06
I think lots of vimmers have got used to the YCM selection style, and if you want them to use another different, if maybe more efficient, completion style, they will feel uncomfortable so that they would stop shifting from vim to atom. Adding this YCM selection style would more vimmers to use atom. So I support adding the YCM selection style.

**Comment by jeancroy** [comment] 2015-11-06 03:30
@evindor 

>2. Instead we expose some of the autocomplete+ functions as services — confirm, set default index, move up/down

you can probably use those command

`autocomplete-plus:move-up`, `autocomplete-plus:move-down`
https://github.com/atom/autocomplete-plus/blob/master/lib/suggestion-list.coffee#L21

`autocomplete-plus:confirm`
https://github.com/atom/autocomplete-plus/blob/master/lib/suggestion-list.coffee#L55

Also if this is the default behavior of VIM, it may find a happy home in VIM-mode package.

**Comment by adambuczynski** [comment] 2016-02-15 20:33
Is there any movement on this issue? I think it would actually address https://github.com/atom/autocomplete-plus/issues/490#issuecomment-184376803 as well, as we could remove TAB and ENTER from being auto complete triggers, and instead use up/down to select a match (which you use most of the time anyway to select a match).

**Closed** 2016-09-20 03:30 UTC
Labels: enhancement

**Comment by JonasT** [comment] 2017-01-16 18:14
@adamreisnz yup it sounds like a really good more reasonable default choice to avoid tabs or newlines getting eaten in stuff I actually wanted to regularly type... (surprise, not everyone is writing C/C++ or something that has `;` line terminators!)

**Comment by adamreisnz** [comment] 2017-01-16 18:19
@JonasT there seems to be a new setting:

![image](https://cloud.githubusercontent.com/assets/490562/21994548/1bbd64f0-dc85-11e6-8ea2-6b7f1f3b3d98.png)

I think this is probably quite useful, as now `ENTER` doesn't auto complete the item unless you've explicitly selected it by moving up/down.

**Comment by JonasT** [comment] 2017-01-16 18:21
@adamreisnz yea, but as I have written in #490 I really think this should be the default, rather than the current "tab and enter" which actually seems to be "tab or enter" which is very troublesome for non-C/C++/Java style languages.

**Comment by adamreisnz** [comment] 2017-01-16 18:25
Probably it should be, yes. But I think the trouble with changing defaults is that a lot of people that are used to the current default might not understand why their autocomplete is suddenly not working as expected.

**Comment by JonasT** [comment] 2017-01-17 01:59
@adamreisnz sure, but that is unavoidable. Maybe a release notes popup would be helpful for things like this?

**Comment by phorust** [comment] 2017-01-28 01:41
hi all,

I got bored and revisited this, and I've got a fix that just requires adding to `keymap.cson` and `init.coffee`.

```
'atom-text-editor:not(mini).autocomplete-active':
  'enter'    : 'autocomplete-plus:confirm'
  'tab'      : 'core:move-down'
  'shift-tab': 'core:move-up'
  '.'        : 'custom:ycm-style-complete-dot'
```

```
atom.commands.add 'atom-text-editor', 'custom:ycm-style-complete-dot', (e) ->
  atom.commands.dispatch(e.currentTarget, 'autocomplete-plus:confirm')
  atom.workspace.getActiveTextEditor()?.insertText('.')
```

Example just has `.` mapped but I mapped all the characters I care about as a JS dev `.([{)]}"' ;` in my full config:

https://gist.github.com/phorust/9eb164cdbd4ceb0b64dda6679a698d5b

found the `autocomplete-plus` source itself not very friendly but I'm sure it could be done in the plugin itself, just seems unlikely that it'd get merged. hope this helps.
