### ISSUE TITLE
Autocomplete jumps around as you type.

### ISSUE THREAD

**Issue by jordwalke** [atom/autocomplete-plus#685] opened 2016-03-09 06:32 UTC
If you are autocompleting such that the autocomplete drop down is towards the *right* side of your screen (so it is almost touching the right side of the entire window), then typing makes the autocomplete window jump around. The best case to see this is when the completion window has one entry in it, and you are typing more of the entry so that the bold match portion increases with each key-stroke. This is very distracting.

**Comment by lee-dohm** [comment] 2016-03-10 19:08
I believe that this is caused by the same underlying problem as #680. I'm going to close this as a duplicate of that Issue. If you have any clarifications that might help the developers, please add them there. You may also want to subscribe to that Issue for updates.

Thanks for reporting!

**Closed by lee-dohm** 2016-03-10 19:08 UTC
