### ISSUE TITLE
Regression in Subsequence provider's support for dashes.

### ISSUE THREAD

**Issue by phyllisstein** [atom/autocomplete-plus#939] opened 2018-01-02 02:19 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Hey folks! I've noticed some odd behavior in how Atom completes terms with dashes in them. It seems to be a regression to what's described in #287: Atom ignores any part of the prefix up to the dash and inserts the whole suggestion, resulting in something like `prefix-prefix-suggestion`.

![screenflow](https://user-images.githubusercontent.com/2207980/34472870-04b50110-ef39-11e7-9fe9-89d4f555c0e4.gif)

I've been able to reproduce this in Atom (v1.23.1), Atom Beta (v1.24.0-beta1), and the current `master` (atom/atom@c97e8f084c91c95d9693e28e38aa9a00b5fdca37), with at least two completion providers.

### Steps to Reproduce

1. Begin typing a term with a dash (try Atom Typescript's module completion, e. just one g., or JSON IDE's completions for TSLint).
2. Accept a suggestion.
3. :boom:

**Expected behavior:** Atom should insert the suggestion, but skip the prefix.

**Actual behavior:** Atom inserts the suggestion, including any prefix characters preceding the dash.

**Reproduces how often:** 100% of the time.

### Versions
* v1.23.1
* v1.24.0-beta1
* `atom/atom#master` (atom/atom@c97e8f084c91c95d9693e28e38aa9a00b5fdca37)

### Additional Information
💖

**Comment by nathansobo** [comment] 2018-01-03 20:40
@damieng @daviwil  I can't seem to get the `ide-json` package working to investigate this. I can get output from the TypeScript server, but not JSON.

**Comment by lonekorean** [comment] 2018-01-10 02:32
I am seeing this issue as well, in version 1.23.3.

Steps to reproduce:
1. Install autocomplete-font-awesome package
2. Create new file (unsaved)
3. Type "fa-gla" to trigger an autocomplete suggestion
4. Accept suggestion
5. Notice "fa-fa-glass" is there, instead of the expected "fa-glass"

Relevant code: https://github.com/lonekorean/atom-autocomplete-font-awesome/blob/master/lib/icons-provider.js

Hope that helps reproduce the issue. Thanks!

**Comment by lonekorean** [comment] 2018-01-11 18:32
FWIW, I was able to work around this by manually setting replacementPrefix in the suggestion objects to the prefix.

So my master branch (linked above) won't repro the issue anymore, but this older release should: https://github.com/lonekorean/atom-autocomplete-font-awesome/tree/v0.2.3

**Comment by rolandixor** [comment] 2018-01-17 21:57
I can confirm this issue. Switching between symbol and subsequence providers makes no difference.

**Comment by nathansobo** [comment] 2018-01-18 17:58
I'm not able to reproduce the issue with autocomplete-font-awesome@0.2.3 and Atom 1.23.3. What language are you autocompleting within?

**Comment by rolandixor** [comment] 2018-01-18 18:51
HTML + CSS. I'm having issues with my own CSS frameworks.

**Comment by lonekorean** [comment] 2018-01-18 18:53
Hm, weird. I removed my fix and still see it (on Win and Mac, Atom 1.23.3, autocomplete-plus 2.40.0).

I do know that the bug does NOT happen in .html files. I just reproed in a .php file, so maybe try that?

**Comment by rolandixor** [comment] 2018-01-18 20:26
Sorry I just realized that the issue I have is slightly different. If I type "round-" for instance, I'll get the correct suggestion of "round-about" (the name of a class). If I type "round3", for example, I get no suggestions (I should get "round-about3" or "round-about13".

**Comment by rolandixor** [comment] 2018-01-19 21:29
Okay, upon further investigation (when you're busy you don't always notice the details):

It is indeed broken in general, but here's how it works. If I type:

"rounda" - the fuzzy search does not activate.

However, if I type "round-" the full list of "round-about" class is shown.

In other words, anything with dashes is ignored unless you type up to the point with the dash. I hope this description makes sense.

**Comment by nathansobo** [comment] 2018-01-19 21:35
@ungb or @rsese do you think you can help me get some clarity on what's going on here? I'm having trouble reproducing but I'm sure there's something wrong.

**Comment by rolandixor** [comment] 2018-01-19 22:01
I've also noticed fuzzy matching is generally having issues. Should I open a separate bug?

**Comment by ungb** [comment] 2018-01-19 23:24
>I've also noticed fuzzy matching is generally having issues. Should I open a separate bug?


@rolandixor I would open an issue and have a reference to this issue for tracking.  Thanks!

>@ungb or @rsese do you think you can help me get some clarity on what's going on here? I'm having trouble reproducing but I'm sure there's something wrong.

@nathansobo I couldn't repro the issue either, but unsure if I have my configuration correct.  @phyllisstein can you provide the list of packages you have install?  you can find this by running `apm list`

**Comment by rsese** [comment] 2018-01-19 23:36
I was also unable to reproduce with autocomplete-font-awesome with Atom 1.23.3, I saw exactly what's in @nathansobo's GIF on macOS 10.12.6 and Windows 10 in a PHP file.

**Comment by rsese** [comment] 2018-01-20 00:05
Ohhhh sorry, I was able to reproduce - I installed the latest autocomplete-font-awesome at first.  If   I install autocomplete-font-awesome at version 0.2.3 I see it:

![ac-bug](https://user-images.githubusercontent.com/734194/35177168-229ebc76-fd43-11e7-8db0-da3b174f5738.gif)

Like @lonekorean mentioned, I don't see this in an HTML file.

**Comment by ungb** [comment] 2018-01-20 00:44
+1 on https://github.com/atom/autocomplete-plus/issues/939#issuecomment-359123740

Repro steps: 
1. run `apm remove autocomplete-font-awesome`
1. run `apm install  autocomplete-font-awesome@0.2.3`
1. Open Atom
1. Create a file called `test.php`
1. Add the following to file:
```php
<?PHP
 <i class=""></i>
?>
```
1. inside "" start typing fa-
1. Click enter on the first autocomplete(for me it's fa-glass).


Expected: autocomplete to `fa-glass`

Actual: autocomplete to `fa-fa-glass`

**Comment by phyllisstein** [comment] 2018-01-20 09:52
Just caught it with the `.` character as well:

![screenflow](https://user-images.githubusercontent.com/2207980/35182179-a8760160-fd9d-11e7-873a-ffd4643385b5.gif)

**Comment by allygator** [comment] 2018-02-20 15:32
This is also happening in css files when using @media, the autocomplete suggests "@media" when the first letter is typed, but when selected I get "@@media"

**Comment by nathansobo** [comment] 2018-02-22 17:33
@allygator Your problem is unfortunate but is actually not related to this issue. What you're seeing is the autocompletion of a snippet to insert media queries. This snippets starts with `media`, not `@media`, which is why you're seeing the `@` stay around. Admittedly, this needs refinement, but it's not clear what behavior would be good in this case and also apply universally. Maybe snippets need to be able to specify multiple prefixes, so that `media` could also have `@media`, and we could choose the most specific one. As a workaround, you could just type the snippet's prefix `media`. Sorry.

As for the actual issue here, we're able to reproduce it on Atom 1.24, but not on Atom 1.25, which is currently in beta and should be hitting stable in March. I'm going to close this out.

**Closed by nathansobo** 2018-02-22 17:33 UTC
