### ISSUE TITLE
Replaces text after the cursor when it equals the suggestion

### ISSUE THREAD

**Issue by saschagehlich** [atom/autocomplete-plus#468] opened 2015-05-18 14:51 UTC
Weird behavior, I think a gif explains it best:

![autocomplete-plus-bug](https://cloud.githubusercontent.com/assets/119684/7683268/224f167a-fd7e-11e4-9e00-b661a37b3d30.gif)

**Comment by joefitzgerald** [comment] 2015-05-18 14:59
I think this is a prefix replacement issue, because the prefix is identical to part of the suffix.

**Comment by benogle** [comment] 2015-07-21 23:48
I think this is not a bug. I am inclined to close this as a wontfix. Do you think the suffix needs to look for a word boundary?

**Comment by antcodd** [comment] 2015-09-19 10:15
What is a valid use case for this behaviour?

It doesn't work correctly with snippets (and thus functions with parameters) as it doesn't strip the special characters. Essentially most of the time that this suffix matching actually works is in confusing cases such as the above and  #510, where the single closing `)` is the "suffix". #510 is almost enough to stop me using atom altogether. It is also rather irritating if attempting to prepend a parameter or variable assignment to a function call as could easily be the reason for the duplication in #559.

Personally I think this is only useful when there is an exact match, or perhaps if the prefix plus the suffix ending at a word boundary is a match for the beginning of the completion. Perhaps a reasonable compromise is a setting plus to stop checking at `@bracketMatcherPairs` or other non-word characters? It should also not match short matches with partial words (e.g. `int foo; foo|foobar()` => `foobar()`).

A possibly useful behaviour of exact matching with snippets would be to re-parse the snippet tab completion, not sure if that is possible (and is obviously a different issue).
It is a shame that completion providers don't provide the text before the `(` separately.

**Closed** 2015-10-02 17:40 UTC
Labels: bug
