### ISSUE TITLE
Reduce the fuzzying

### ISSUE THREAD

**Issue by peterbe** [atom/autocomplete-plus#564] opened 2015-08-27 21:17 UTC
I typed `continue` in python and this suggestion popped up:

![screenshot 2015-08-27 14 12 50](https://cloud.githubusercontent.com/assets/26739/9533274/d91e3f0c-4cc5-11e5-9d5e-2dc0a821de70.png)

The highlighting inside the autocomplete suggestion tooltip seems to indicate that it found it because of the `Co` and the `nt` and the `i` and the `n` and the `u` and the `e`. 
But it's totally different! :)

When I have typed so much ("continue" is 9 characters), couldn't the fuzzyaldrin (or whatever it's called) take that into account? It'd make sense to suggest "CommentsBySignature" if I had typed `co` (or even `con` with one edit distance). 

This is not a rare case. Just that I really noticed it this time because it's a great example of how overly optimistic the fuzzying matcher is.

**Comment by peterbe** [comment] 2015-08-27 21:19
So, why do I "complain"?

Well, suggestions are easy to ignore **if** the next thing you do is to type a space character. 
But in this case, after having typed `continue` in Python I'm going to hit Enter to go to the next line and if I do that it replaces my `continue` with `CommentsBySignature` which sucks so I have to always press Escape before I can finish that line.

**Comment by peterbe** [comment] 2015-08-27 21:20
A more or equally pressing concern is; why isn't `continue` a alternative to autocomplete? It's been typed at least 4 other times in this file I'm editing and the word `continue` is common in the project. Much more common than `CommentsBySignature`.

**Comment by peterbe** [comment] 2015-08-27 21:21
Sorry if I come across with a "tone". I love autocomplete-plus and it often saves me typos because the guesses are pretty good.

**Comment by jeancroy** [comment] 2015-08-27 21:49
Hi peterbe.
I believe it's OK to allow very fuzzy result as long as obvious result come first.
And certainly `continue` would come before `CommentsBySignature`

So what happens here ?
One possibility is that some provider will not suggest what is already typed. IE `continue` is not on the list because there's nothing to complete from the typed `continue`

If you type `cont` an continue does not appear, then it's a different issue.

**Comment by peterbe** [comment] 2015-08-27 22:02
If I type `continu` (missing the last `e`) it certainly suggests `continue` but the other suggestions are incredibly far from relevant. 
![screenshot 2015-08-27 14 58 48](https://cloud.githubusercontent.com/assets/26739/9534288/3bdf0012-4ccc-11e5-8849-65f9016763d3.png)

If have bothered to type 8 characters I have really started to form an opinion on what I'm going to type. 

I think the fuzzying matcher needs to take this into account. The number of edit distances between `continu` and `CommentsBySignature[:8]` is **6** which should tell it to give up IMHO.

**Comment by jeancroy** [comment] 2015-08-28 02:10
For a spell checker, this would be a perfectly valid behavior.

However sublime text among other popularized selecting  using a sub-sequence. This is what you see. 
In your particular case it does not make much sens, but it use the same rule as when it does make sens. As long as the obvious answer is on top the other results are not much important.

What I start to gather is that it is easy to do an accidental accept of auto-complete. Maybe the key binding / timing is the underlying issue. Maybe the rule that hide continue while already typed is a problem.

**Comment by 50Wliu** [comment] 2015-08-28 13:59
> Maybe the rule that hide continue while already typed is a problem.

If it's shown, that's also an annoying issue, because you'll need to hit enter twice instead of once when trying to get to a new line.

**Comment by peterbe** [comment] 2015-08-28 15:28
> If it's shown, that's also an annoying issue, because you'll need to hit enter twice instead of once when trying to get to a new line.

"enter twice"?? You mean, first Escape (to kill the autocomplete) and *then* Enter. This happens almost always when I type a multi-line comment.

**Comment by jeancroy** [comment] 2015-08-28 18:47
> If it's shown, that's also an annoying issue, because you'll need to hit enter twice instead of once when trying to get to a new line.

Among the two evil I believe pressing enter twice is better than having the current word replaced by something else unintentionally. (And probably having to press enter twice anyways). 

The `not showing prefix` rule is also the cause of that case sensitive confusion https://github.com/atom/autocomplete-plus/issues/42#issuecomment-133878090

And possibly the source of people not wanting autocomplete to be enabled https://github.com/atom/autocomplete-plus/issues/552

----

I'm starting to think a *Primum non nocere* approach might be what we need. Like if the auto-complete is automatically triggered, do not select any result by default, let `enter` do it's job of making a newline.

**Comment by jeancroy** [comment] 2015-08-28 19:01
And to be fair with peterbe, we are not totally powerless in accepting those fuzzy matches.

Usage of the sub-sequence feature is mostly useful on acronyms.

<img width="595" alt="740fdeb2-2548-11e5-8a14-dfb2155e31bd 1" src="https://cloud.githubusercontent.com/assets/12763666/9554552/9a258114-4d94-11e5-96f3-17398a00f0ca.png">

So a rule like 
-  at least half the letter must 
    - be part of either a word boundary 
    - or a group of at least two consecutive letter

could set a baseline for relevance. The problem is that your bad results would pass that rule. We can bump it to 3/4 but then `ssrb` would barely pass. It's hard to but a minimum accuracy without sample of what people use.

**Comment by peterbe** [comment] 2015-08-28 19:29
I very much like the idea that Enter after typing doesn't select the first autocomplete suggestion. I these days often find myself typing something then Escape then typing something then Escape to get rid of the overly eager autocomplete. 
Prior to Atom I used an editor where I always had to make a conscious choice to find autocomplete suggestions. An advantage with that is that it rarely gets these terrible examples (e.g. `continue !!= CommentsBySignature`) and that the IDE doesn't use so damn much resources. :)

**Comment by peterbe** [comment] 2015-08-28 19:35
The `ssrb` example is tricky because on one hand "Set Syntax" and the "ss" makes sense because they are initials. However, the "Ruby ~= rb" example is pretty nifty. 

However "ssrb" is only four characters, so there's still a chance that autocomplete will help me. However "continue" is 9 characters. If I've typed that many characters before I contemplate the autocomplete options I think I've made up my mind more. 

In the same sense, I've I've taken the time to type `CaseSe` I've committed to bother to type uppercase and I've typed a lot so I would not like it to suggest "casesensitivity" as an autocomplete option. 

If, inside the fuzzyaldrin "engine", there's some sort of threshold, it would be good if that could become dynamic. E.g 4 edit distances max if you've type 5 or more characters, otherwise 6 edit distances. Or something like that.

**Comment by peterbe** [comment] 2015-08-28 19:36
Again, thank you for your patience. The code is awesome. But it can still be improved. I'm just speaking straight from my gut and that's from real actual use.

**Comment by jeancroy** [comment] 2015-08-28 21:49
> If I've typed that many characters before I contemplate the autocomplete options I think I've made up my mind more. 

The thing is a query with a lot of character could be
  - user already typed what was needed. (As you suggest)
  - user need to type a long query because of multiple similar result 
  - user just have a preference for long query.

For example: 
`LctFnMxm` could match **L**o**c**a**t**e**F**u**n**ction**M**a**x**i**m**um 
Query have 8 chars, 12 edit distance, but otherwise perfectly valid.

**Comment by peterbe** [comment] 2015-08-28 22:16
I have to admit, this practice of typing things like "LctFnMxm" is new to me. Maybe I'm just an old fart. 
I can't think of any other applications where I explain autocomplete to break apart what I've typed. E.g if I type `Aaaa` it could technically find "**A**l**A**b**A**m**A**" but I can't imagine it being something many users would expect when they type "aaaa". 

Is there a name for this? Could enabling/disabling that be an interesting configuration option?

**Comment by jeancroy** [comment] 2015-08-29 01:04
What I meant is that just like `ruby` can be shortened as `rb`, `function` can be as `fn`, `javascript` as `js`, `point`as `pt` and `pixel` as `px` and so forth. And it's not impossible to mix and match those in a query. 

One thing that does not help is that fuzzaldrin is used by many part of atom: In "command palette" you know you are selecting so it's OK to type as few letter as possible (like `ssrb`).  In  "fuzzy finder" people type query mixing folder and file name, even sometime without a `/` and expect things to just work. In "autocomplete" however, normal word will get passed to the fuzzy engine for no other reason than waiting 100ms. And that might cause accidents if it's too easy to accept a match.

**Comment by jeancroy** [comment] 2015-08-29 01:14
Overall "LctFnMxm" and every other example is selection using a sub-sequence of character.  A bit like an edit distance where insertion is free, deletion and substitution/transpose have infinite cost. And I'm not even sure what can be turned off to prevent "LctFnMxm". It's just a natural result of using sub-sequence.

Because every suggestion contain every char of the query in correct order, the edit distance can be simplified to the difference of length of both string. Something like match up to 12 char for query below 6, and n+6 for query of size n>6.

However the proper setting for that is VERY context dependent. For example 12 char is very small for a path.  Also `LFM` could not be used to match `LocateFunctionMaximum` because there would be 18 edit distance. 

Finaly should you ever work in a ukulele factory, you'll be back at square one because you may find a "**cont**a**in**s_**u**k**e**" variable that mess with your continue (edit distance 4).

**Comment by jeancroy** [comment] 2015-08-29 03:39
Limit on the number of error is very hard to set. For example `LCM` -> `LocateFunctionMaximum` is 18 edit distance. While `continue` -> `containsUE` is 2 edit distance (UE = user exprerience?). So nothing really make us safe from unwanted replacement.

Visual Studio Code (which is basically a Microsoft clone of atom) have an interesting way to handle fuzzy matching. I from what I understand, one can either add a character to existing sequence or jump to the next word. For example having typed `LF` the 2 legal option to match `LocateFunctionMaximum
` would be `u` or `M`

As an added bonus that kind of fuzzy but still rigid allow to precompute a search index.

**Comment by jeancroy** [comment] 2015-08-29 04:03
Ok i've checked against sublime text which is seen as having a good auto complete. (sorry for image size)

1) Suggestions are shown.
![Screen1](https://i.gyazo.com/c698660dd6edd08584e5dedb644d0bff.png)

2) Continue allow to stay (and yes we need to enter twice)
![Screen2](https://gyazo.com/d93ddd81d2412e31fc80c9f5268a936a.png)

3) Uppercase not strictly enforce but rank better.
![Screen2](https://gyazo.com/4cd56790f1aa3e4a3d5a4de1f68c77ac.png)

**Comment by wmayner** [comment] 2015-09-03 00:20
IMHO:
- The super-fuzzy substring matching is a fantastic feature (though it does take some getting used to), and it's consistent with the behavior elsewhere in Atom, and in other apps (*e.g.* Sublime or the YouCompleteMe completion plugin for Vim).
- As others have pointed out, *the real problem is the `Enter` keybinding.*

Proposed Solution: **Only the `Tab` key should accept suggestions!**

Pros:
- *Keep it simple, stupid!* One less behavior to figure out, implement, and maintain; one less keybinding to keep track of.
- Principle of least astonishment (as you say, the current behavior is pretty astonishing).
- Consistent with the command-line.

Cons:
- Inconsistent with other menu selection boxes.
- I'll leave the rest of these up to you folks :smile_cat:

**Comment by jeancroy** [comment] 2015-09-03 00:52
Honestly tab to cycle and enter to accept is pretty much a standard.
And enter to accept first entry make sens when you manually invoke the popup: you know you are selecting from a list.

However enter to accept a "randomly" occurring popup is pretty strong.

Maybe we can have no item selected by default, then use the mouse to select or tab+enter / down+enter to accept with keyboard. When manually invoking the auto-complete, we can have first item selected. It's an extra step but it's also a  confirm step.

I'm pretty sure however than an extra step will trigger an angry mob with torches and pitchforks. Maybe we should just increase the delay before that popup appears.

**Comment by peterbe** [comment] 2015-09-03 14:11
It's not easy. But there's certainly something fishy about the Enter command.

Often, my "frustration" (ie. things we can improve) stems two scenarios.

1. When I have typed a full term that already exists but is not the first choice. Hitting enter to start a new line overrides what I had painstakingly typed.
![screenshot 2015-09-03 07 03 40](https://cloud.githubusercontent.com/assets/26739/9660371/2cc0b506-520a-11e5-91a7-8885b0a7fc5d.png)
In this example, it was maybe a mistake to type out the whole of `forms` and not hitting Tab + Enter when I had typed `form` because without the `s` the word `forms` was the number one suggestion. Now that I've typed it, to get to a new line I have to Esc + Enter rather than just Enter. 

2. Similar, if I type a new word that has not been typed before. But said word is the start of another word. 
![screenshot 2015-09-03 07 09 34](https://cloud.githubusercontent.com/assets/26739/9660498/c094ea2c-520a-11e5-9536-8d656494d1a9.png)
Now I can't hit Enter because hitting Enter will accept the first suggestion. However, it's only a problem when I have to hit Enter.

**Comment by peterbe** [comment] 2015-09-03 14:12
Hmm... Maybe both of my above mentioned frustrations can both be solved by changing the setting so that Tab is what selects from the suggestions. Thanks @wmayner I'll look into that.

**Comment by xdumaine** [comment] 2015-09-09 16:29
This one is frustrating me quite a bit 
![image](https://cloud.githubusercontent.com/assets/833911/9767874/5bf9a81c-56ee-11e5-9fa6-23566f40977d.png)

**Comment by peterbe** [comment] 2015-09-09 16:38
If this discussion is leading anywhere it's that it's frustrating when the top-most suggestion isn't the word itself, if the word itself has been written somewhere before. 

So, it's not a matter of "boosting" the words "continue" or "else" or "Environment" to be the first choice because they don't even show up. @xdumaine I'm guessing this isn't the first time you've typed "else" in that project/file.

**Comment by xdumaine** [comment] 2015-09-09 16:56
Right, so basically if the word is an exact match, that exact match should be the first result, and the `confirm` action should choose it, not some other fuzzy match.

**Comment by jeancroy** [comment] 2015-09-09 17:15
There is an assumption being made that if you trigger the autocomplete menu, it's because you want to complete something. If what you have written is what you want - then there's no reason for you to trigger than menu. So it's logical to hide that option.

Where that assumption fail, is that the menu will get auto triggered on timer. Then there's legitimate use for not wanting to complete anything.

**Comment by jeancroy** [comment] 2015-09-09 17:32
Related question : What buffer provider are you using ? Symbol or fuzzy provider ?

**Comment by jeancroy** [comment] 2015-09-09 17:46
@peterbe @xdumaine Is it possible you are using fuzzy provider instead of symbol ?
![35658eee83895275904fbf0be5b2f774](https://cloud.githubusercontent.com/assets/12763666/9769565/f928bc5e-56f8-11e5-9ba9-a9882d68917d.png)

Because that behavior is fixed for symbol I beleive:
![ac70a457cbe33714250aafd253663eae](https://cloud.githubusercontent.com/assets/12763666/9769608/24099f6a-56f9-11e5-833f-086938b1b33e.png)

**Comment by peterbe** [comment] 2015-09-09 17:54
I'm apparently using "Symbol". Version 1.0.11

**Comment by jeancroy** [comment] 2015-09-09 18:18
Using a clean install of atom, python language:

![74d9ae73eaaeadb5b63c351e8a3b578e](https://cloud.githubusercontent.com/assets/12763666/9770309/930495f6-56fd-11e5-92ce-5286232f6e41.png)

Sorry about the huge screenshot.

**Comment by peterbe** [comment] 2015-09-09 18:44
That's exactly what I want! What version and what default provider is that?

**Comment by xdumaine** [comment] 2015-09-10 13:57
I just ran all updates and it seems to be working now. None of the updates looked like they were relevant, so now I'm stumped.

**Comment by eosrei** [comment] 2015-12-04 23:18
@wmayner :+1: `tab` to accept by default.

The default autocomplete-plus autocorrect behavior is quite frustrating. Example:

1. Make a new file named: example.sh
2. Type:
```
EXAMPLE="words"

#This example
```
Now press *Enter* after that last `e` and the entire word becomes capitalized to `EXAMPLE`. It gets worse though, because autocomplete pulls from other open files (which is great, don't get me wrong!). Example:

1. Leave that original open
2. File->New File
3. type the text `example`
4. Press *Enter* to make a new line (the way that you make new lines in every other program.) Result:
```
EXAMPLE
```

The expected way to select auto-complete is *tab* as suggested above or the arrow keys. I know I can change to *tab*, but I really think this default functionality needs to allow users to type newlines in the expected way.

**Comment by irbdavid** [comment] 2016-03-30 18:21
I am surprised to see that purely numeric 'words' are included in the autocomplete dictionary, as I think this is as likely to cause problems as it is to save time.  A setting to disable this would be very welcome.  

![screen shot 2016-03-30 at 6 01 19pm](https://cloud.githubusercontent.com/assets/727275/14152621/74515cdc-f6b4-11e5-93fa-67c2812e191f.png)

**Comment by eedwardsav** [comment] 2017-11-01 18:03
Symbol Matching still isn't working as expected...

![screen shot 2017-11-01 at 1 02 34 pm](https://user-images.githubusercontent.com/31772701/32289570-1116bc3c-bf05-11e7-81de-3c57ee267844.png)

**Comment by Ben3eeE** [comment] 2017-11-02 14:08
@leroix Do you think this is addressed by subsequence and the removal of the fuzzy provider?

**Comment by jeancroy** [comment] 2017-11-02 14:31
hi @Ben3eeE what we see here is that snippet (green arrow) appears before symbols. 
It does this by design even if a lot of us kinda disagree of that design.
https://github.com/atom/autocomplete-plus/issues/465

**Comment by leroix** [comment] 2017-11-03 03:46
@eedwardsav @Ben3eeE I believe this particular situations would be fixed in Atom 1.22. It's worth giving it a try.

**Comment by Ben3eeE** [comment] 2017-11-03 08:09
@leroix The suggestions from `autocomplete-snippets` still sort first and fuzzy even when using the subsequence provider.

I am going to close this in favor of https://github.com/atom/autocomplete-plus/issues/465 thanks @jeancroy for the issue link :bowing_man:

**Closed by Ben3eeE** 2017-11-03 08:09 UTC
Labels: feedback
