### ISSUE TITLE
@media / @import autocomplete results in @@media /@@import

### ISSUE THREAD

**Issue by egomadking** [atom/autocomplete-plus#863] opened 2017-07-02 12:38 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode
    * Followed all applicable steps in the debugging guide
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed
    * Checked that there is not already an Atom package that provides the described functionality

### Description

While editing CSS file, typing `@m` provides the auto-complete option of `@media`. Upon confirm, auto-completion results in `@@media query{}`. Typing `@im` provides the auto-complete option of `@import`. Confirming results in `@@import ""`

**Expected behavior:** [What you expect to happen]

In the case of `@media`, I would expect only to get `@media {}`.
In the case of `@import`, I would expect only to get `@import ""`.

**Actual behavior:** [What actually happens]

In the case of `@media`, I get `@@media query {}`.
In the case of `@import`, I get `@@import ""`.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

I have also tried all combinations of disabling and enabling:
- the built-in provider
- include completion from all buffers
- autocomplete-css
- autocomplete-snippets
- spell-check

**Comment by rsese** [comment] 2017-07-03 22:47
I think this is basically a duplicate of issues like:

https://github.com/atom/autocomplete-plus/issues/788
https://github.com/atom/atom/issues/14934

The snippet in the first case is triggered by `media`, not `@media` - so when you type `@media`, you're getting the `@` followed by the `media` snippet which already includes the `@`.  The issue with `@import` is the same.

So you only need to type `media` and `import` and you won't get the repeated `@`.

**Closed by rsese** 2017-07-03 22:47 UTC
