### ISSUE TITLE
Autocomplete in Markdown Files?

### ISSUE THREAD

**Issue by loveencounterflow** [atom/autocomplete-plus#611] opened 2015-11-13 19:49 UTC
I don't get proper autocomplete in markdown files; the autocomplete package is installed; no exclusions have been set; syntax has been set to Github Markdown; it works in other files, even plain text files.

I'd like to get suggestions gleaned from all words in the current document; ideally, all files w/out configured autocomplete handler should be treated like plain text files, IMHO.

I can confirm that this is propably due to the `language-gfm` package since the issue goes away as soon as I switch the file language to plain text or any other format. However, I can not find where in that package that inhibits autocompletion. 

IMHO if there's a package language-x that changes how package feature-y behaves, such fact should always be made known in the readme of language-x, and be—ideally—configurable for the user; not only that, I'd suggest to make such configuration available from *both* language-x *and* feature-y. At least it would be great if the settings page of feature-y would show which other packages are registered to make changes to the behavior/availability of feature-y.

**Comment by benogle** [comment] 2015-11-17 00:31
Can you post your config file? This definitely works for me.

**Comment by loveencounterflow** [comment] 2015-11-17 08:26
```json
"*":
  "exception-reporting":
    userId: "502a16eb-3108-47be-d521-adeaf12e659c"
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "tab-smart-sort"
      "highlight-column"
      "highlight-line"
      "tree-view"
      "jshint"
    ]
    packagesWithKeymapsDisabled: [
      "tab-smart-sort"
    ]
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    showIndentGuide: true
    preferredLineLength: 108
    invisibles:
      space: "*"
      tab: "%"
      cr: "C"
      lf: "L"
      eol: "↩"
    showInvisibles: true
    fontSize: 16
    autoIndentOnPaste: false
  "filetype-color":
    enabled: "true"
  "highlight-column":
    opacity: 0.05
    enableHighlight: true
  "autocomplete-plus":
    backspaceTriggersAutocomplete: true
    maxVisibleSuggestions: 30
    defaultProvider: "Fuzzy"
    minimumWordLength: 1
    autoActivationDelay: 10
    fileBlacklist: [
      "*.xxxxxxx"
    ]
    useAlternateScoring: true
  whitespace:
    ensureSingleTrailingNewline: false
  "merge-conflicts": {}
  "run-command2": {}
  "tree-view": {}
  "tab-smart-sort":
    placeSpecialTabsOnRight: true
  "highlight-line":
    enableSelectionBorder: true
    enableUnderline: true
    enableBackgroundColor: false
  "tree-view-open-files":
    maxHeight: 0
  "selection-highlight":
    highlightBackground: true
".latex.memoir.tex.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".beamer.latex.tex.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".latex.log.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".latex.tex.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".gfm.source":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".tex.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
".bibtex.text":
  editor:
    nonWordCharacters: "./\\()\"':,.;<>~!@#$%^&*|+=[]{}`~?"
    preferredLineLength: 108
```

**Comment by benogle** [comment] 2015-11-17 20:12
Can you try changing the defaultProvider to "Symbol"?

**Comment by goldsborough** [comment] 2015-12-14 15:51
I think I'm having the same issue, basically the suggestions show up for my Markdown files but the key-bindings just don't work. There's nothing relevant in my keymap to mess things up and for all other grammars the completion-on-tab works perfectly. There's no Markdown-language package I could look at to see if it breaks any keybindings or anything so I don't really know how to fix this one. Definitely extremely annoying though.

Config (OS X 10.11.2):

"*":
  "exception-reporting":
    userId: "6fa3d067-d4f8-8be5-f4fd-9932c2e2b341"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "itg-flat-dark"
      "itg-dark-syntax"
    ]
    disabledPackages: [
      "markdown-preview"
    ]
  editor:
    invisibles: {}
    fontFamily: "Menlo"
    softWrap: true
    softWrapAtPreferredLineLength: true
    tabLength: 4
    showInvisibles: true
    showIndentGuide: true
    tabType: "hard"
    fontSize: 12
  "python-tools": {}
  "linter-pylint":
    rcFile: "~/.pylintrc"
  "linter-pylama":
    executablePath: "/usr/local/bin/pylama"
    ignoreErrorsAndWarnings: "W191"
  minimap:
    absoluteMode: true
  build:
    saveOnBuild: true
  linter: {}
  "ever-notedown": {}
  "spell-check":
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.plain"
      "text.plain.null-grammar"
      "source.litcoffee"
      "text.markdown.evnd.mathjax.source.litcoffee.inline.html"
      "text.markdown.evnd.mathjax.source.gfm.inline.html"
      "text.markdown.evnd.source.gfm.inline.html"
    ]
  latex:
    enableShellEscape: true
    openResultAfterBuild: false
    openResultInBackground: false
  "pdf-view": {}
  "merge-conflicts": {}
  "markdown-preview": {}
  Repl: {}
  "markdown-preview-plus":
    enableLatexRenderingByDefault: true
    breakOnSingleNewline: true
    useGitHubStyle: true
  "find-and-replace":
    focusEditorAfterSearch: true
    useRegex: true
    caseSensitive: true
  "markdown-writer": {}
  "markdown-themeable-pdf": {}
  "autocomplete-python": {}
  "autocomplete-plus":
    backspaceTriggersAutocomplete: true
    confirmCompletion: "tab"

**Comment by loveencounterflow** [comment] 2015-12-14 15:56
so I tried to set the Symbol Provider in the autocomplete-plus settings page to "Symbol", restarted Atom, and it does seem to work!

**Comment by logista** [comment] 2015-12-17 03:01
I can't get autocomplete inside markdown files, no matter which Provider I choose. I've tried turning off `language-gfm` in favor of `language-pfm` but it didn't help. Autocomplete gives me options, but won't expand any of the choices, not with `tab` nor with `enter`

Mac OS X 10.10.5

**Comment by goldsborough** [comment] 2015-12-17 12:42
^ Exactly my problem too.

**Comment by goldsborough** [comment] 2015-12-27 15:36
Ok so for me there was a keybinding conflict between autocomplete and the markdown-writer package, which defined the tab key for indenting lists. Viewing the keybinding-resolver via `cmd+.` (command then plus then dot) helps.

**Comment by logista** [comment] 2015-12-27 18:28
Thanks, @goldsborough ! That helps a lot. I disabled `markdown-writer` and got tab-complete back.

**Comment by logista** [comment] 2015-12-30 18:29
It seems as though `markdown-writer` has [fixed this](https://github.com/zhuochun/md-writer/commit/c34ae11e787d099a750d09c654e4677cc35eed41)

**Comment by lee-dohm** [comment] 2015-12-30 18:59
Since it sounds like everyone that has mentioned that this didn't work for them is now saying that it is fixed, I'm going to close this Issue. Please let us know if this reproduces for anyone!

**Closed by lee-dohm** 2015-12-30 18:59 UTC
Labels: more-information-needed
