### ISSUE TITLE
enter when suggestion explicitly selected

### ISSUE THREAD

**Issue by ChrisIdema** [atom/autocomplete-plus#1060] opened 2019-08-08 12:31 UTC
'tab always, enter when suggestion explicitly selected' option is convenient but still not optimal,
'enter when suggestion explicitly selected' option would be better. 

Right now autocomplete-plus is too arrogant and automatically inserts suggestions without my permission. I only want a suggestion confirmed if I confirmed it with arrow keys and enter, not with tab.

**Comment by rsese** [comment] 2019-08-08 19:14
Thanks for the suggestion!

We noticed that this looks like a duplicate of https://github.com/atom/autocomplete-plus/issues/943 so you can subscribe there for updates if you'd like.

For future issues, please fill out the issue template or your issue may be closed.  The information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-08 19:14 UTC
