### ISSUE TITLE
Automatically add highlighted suggestion

### ISSUE THREAD

**Issue by mikew** [atom/autocomplete-plus#545] opened 2015-07-23 15:09 UTC
In Vim, you don't need to press anything to "confirm" the current selection, simply highlighting it adds it. Would it be possible to add this to autocomplete-plus?

**Comment by benogle** [comment] 2015-07-23 17:19
Closing as a duplicate of https://github.com/atom/autocomplete-plus/issues/240

**Closed by benogle** 2015-07-23 17:19 UTC
